TikTakToe: hal/interrupts.c File Reference
interrupts.c File Reference
Implements the interrupt handlers for UART and Timer interrupts.
#include "hal/interrupts.h"
#include "hal/nvic.h"
#include "hal/register_access.h"
#include "hal/timer.h"
#include "hal/uart.h"
#include "logic/time.h"
#include "util/input_buf.h"
Functions
void Interrupt2_Handler ()
UART interrupt handler.
void Interrupt8_Handler ()
Timer interrupt handler.
Detailed Description
Implements the interrupt handlers for UART and Timer interrupts.
See also
interrupts.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file interrupts.c.
Function Documentation
Interrupt2_Handler()
void Interrupt2_Handler ()
UART interrupt handler.
This function is triggered when a UART interrupt occurs. It reads a byte from the UART peripheral and processes it using the input buffer. The interrupt pending bit is cleared after handling the interrupt.
See also
uart_readByte
Definition at line 23 of file interrupts.c.
References input_onInterrupt(), Interrupt_ICPR, Interrupt_ID2, register_write(), and uart_readByte().
Interrupt8_Handler()
void Interrupt8_Handler ()
Timer interrupt handler.
This function is triggered when a timer interrupt occurs. It resets the timer compare register and clears the interrupt pending bit. Additionally, it notifies the time module about the interrupt event.
See also
time_onInterrupt
Definition at line 29 of file interrupts.c.
References Interrupt_ICPR, Interrupt_ID8, register_write(), time_onInterrupt(), TIMER0_BASE_ADDRESS, and TIMER_COMPARE_0.