TikTakToe: presentation/cursor.h File Reference
cursor.h File Reference
Contains function for moving the presentation of the cursor.
#include <stdint.h>
Functions
void cursor_moveTo (uint8_t x, uint8_t y)
Move cursor to the given coordinates.
Detailed Description
Contains function for moving the presentation of the cursor.
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file cursor.h.
Function Documentation
cursor_moveTo()
void cursor_moveTo (uint8_t x, uint8_t y)
Move cursor to the given coordinates.
Parameters
[in] x X-Position
[in] y Y-Position
Definition at line 32 of file cursor.c.
References int_to_str(), print(), and writeNumToBuf().