TikTakToe: util/input_buf.c File Reference
input_buf.c File Reference
Implementation of the input buffer functions.
#include "util/input_buf.h"
#include "presentation/print.h"
#include "util/error_handling.h"
Functions
static bool putIntoBuf (volatile InputBuffer *ib, const uint8_t byte)
Put the next byte into the buffer.
void input_onInterrupt (const uint8_t input)
Function to call in case of UART input interrupt.
void input_init (volatile InputBuffer *ib)
Initialize the given InputBuffer.
bool input_isEmpty (const volatile InputBuffer *ib)
Check if the buffer is empty.
bool input_isFull (const volatile InputBuffer *ib)
Check if the buffer is full.
bool input_getNext (volatile InputBuffer *ib, uint8_t *byte)
Get the next byte from the buffer.
Variables
volatile InputBuffer g_input_buf
Global input buffer instance.
Detailed Description
Implementation of the input buffer functions.
This file contains the implementation of functions for managing the input buffer, including initialization, checking buffer state, and handling UART input interrupts.
See also
input_buf.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file input_buf.c.
Function Documentation
input_getNext()
bool input_getNext (volatile InputBuffer * ib, uint8_t * byte)
Get the next byte from the buffer.
Parameters
[in,out] ib InputBuffer to read from.
[out] byte Pointer to store the next byte.
Returns
False if the buffer is empty, true otherwise.
Definition at line 67 of file input_buf.c.
References InputBuffer::data, INPUT_BUF_SIZE, input_isEmpty(), and InputBuffer::tail.
input_init()
void input_init (volatile InputBuffer * ib)
Initialize the given InputBuffer.
Parameters
[in,out] ib InputBuffer to initialize.
Definition at line 51 of file input_buf.c.
References InputBuffer::head, and InputBuffer::tail.
input_isEmpty()
bool input_isEmpty (const volatile InputBuffer * ib)
Check if the buffer is empty.
Parameters
[in] ib InputBuffer to check.
Returns
True if the buffer is empty, false otherwise.
Definition at line 57 of file input_buf.c.
References InputBuffer::head, and InputBuffer::tail.
input_isFull()
bool input_isFull (const volatile InputBuffer * ib)
Check if the buffer is full.
Parameters
[in] ib InputBuffer to check.
Returns
True if the buffer is full, false otherwise.
Definition at line 62 of file input_buf.c.
References InputBuffer::head, INPUT_BUF_SIZE, and InputBuffer::tail.
input_onInterrupt()
void input_onInterrupt (uint8_t input)
Function to call in case of UART input interrupt.
Parameters
[in] input Pure input from UART.
Definition at line 41 of file input_buf.c.
References g_input_buf, and putIntoBuf().
putIntoBuf()
static bool putIntoBuf (volatile InputBuffer * ib, const uint8_t byte) static
Put the next byte into the buffer.
This function writes a byte into the input buffer if there is space available.
Parameters
[in,out] ib InputBuffer to write to.
[in] byte Byte to write into the buffer.
Returns
False if the buffer is full, true otherwise.
Definition at line 78 of file input_buf.c.
References InputBuffer::data, InputBuffer::head, INPUT_BUF_SIZE, and input_isFull().
Variable Documentation
g_input_buf
volatile InputBuffer g_input_buf
Global input buffer instance.
Definition at line 24 of file input_buf.c.