TikTakToe: util/input_buf.h File Reference
input_buf.h File Reference
Contains everything for the input buffer.
#include "def.h"
#include <stdint.h>
Data Structures
struct InputBuffer
RingBuffer for fixed memory footprint.
Macros
#define INPUT_BUF_SIZE 128
Functions
void input_onInterrupt (uint8_t input)
Function to call in case of UART input interrupt.
void input_init (volatile InputBuffer *ib)
Initialize the given InputBuffer.
bool input_isEmpty (const volatile InputBuffer *ib)
Check if the buffer is empty.
bool input_isFull (const volatile InputBuffer *ib)
Check if the buffer is full.
bool input_getNext (volatile InputBuffer *ib, uint8_t *byte)
Get the next byte from the buffer.
Variables
volatile InputBuffer g_input_buf
Detailed Description
Contains everything for the input buffer.
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file input_buf.h.
Macro Definition Documentation
INPUT_BUF_SIZE
#define INPUT_BUF_SIZE 128
Definition at line 19 of file input_buf.h.
Function Documentation
input_getNext()
bool input_getNext (volatile InputBuffer * ib, uint8_t * byte)
Get the next byte from the buffer.
Parameters
[in,out] ib InputBuffer
[out] byte Next Byte
Returns
False if empty
Definition at line 59 of file input_buf.c.
References InputBuffer::data, INPUT_BUF_SIZE, input_isEmpty(), and InputBuffer::tail.
input_init()
void input_init (volatile InputBuffer * ib)
Initialize the given InputBuffer.
Parameters
[in,out] ib InputBuffer
Definition at line 43 of file input_buf.c.
References InputBuffer::head, and InputBuffer::tail.
input_isEmpty()
bool input_isEmpty (const volatile InputBuffer * ib)
Check if the buffer is empty.
Parameters
[in] ib InputBuffer
Returns
True if empty
Definition at line 49 of file input_buf.c.
References InputBuffer::head, and InputBuffer::tail.
input_isFull()
bool input_isFull (const volatile InputBuffer * ib)
Check if the buffer is full.
Parameters
[in] ib InputBuffer
Returns
True if full
Definition at line 54 of file input_buf.c.
References InputBuffer::head, INPUT_BUF_SIZE, and InputBuffer::tail.
input_onInterrupt()
void input_onInterrupt (uint8_t input)
Function to call in case of UART input interrupt.
Parameters
[in] input Pure input from UART
TODO Handle error better
Definition at line 34 of file input_buf.c.
References g_input_buf, print(), and putIntoBuf().
Variable Documentation
g_input_buf
volatile InputBuffer g_input_buf extern
Definition at line 22 of file input_buf.c.