TikTakToe: logic/time.h File Reference
time.h File Reference
#include "logic/game.h"
#include <stdint.h>
Data Structures
struct GameTimer
Functions
void time_init ()
Initializes the timer.
void time_onInterrupt ()
Increments the ticks and can finish the round.
void time_finishTurn (GameState *game_state)
Resets the ticks.
void time_pause ()
void time_resume ()
Variables
GameTimer g_timer
Detailed Description
Author
Date
See also
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file time.h.
Function Documentation
time_finishTurn()
void time_finishTurn (GameState * game_state)
Resets the ticks.
Definition at line 47 of file time.c.
References GameState::circle_total_ticks, Cross, GameState::cross_total_ticks, GameState::current_player, g_timer, game_state, and GameTimer::ticks_turn.
time_init()
void time_init ()
Initializes the timer.
Definition at line 30 of file time.c.
References CC0, TICK_SPEED, TIMER0, TIMER_BIT_MODE_32, timer_captureCompareSet(), timer_init_detailed(), TIMER_MODE_TIMER, and timer_start().
time_onInterrupt()
void time_onInterrupt ()
Increments the ticks and can finish the round.
Definition at line 37 of file time.c.
References g_timer, game_onTimeOut(), TICKS_PER_TURN, GameTimer::ticks_total, and GameTimer::ticks_turn.
time_pause()
void time_pause ()
Definition at line 63 of file time.c.
References g_timer, GameTimer::is_running, TIMER0, and timer_stop().
time_resume()
void time_resume ()
Definition at line 69 of file time.c.
References g_timer, GameTimer::is_running, TIMER0, and timer_start().
Variable Documentation
g_timer
GameTimer g_timer extern
Definition at line 24 of file time.c.