TikTakToe: presentation/print.c File Reference
print.c File Reference
#include "presentation/print.h"
#include "hal/uart.h"
#include "presentation/style.h"
#include "util/conversion.h"
Functions
void print_clearConsole ()
Clear the whole terminal.
void print (const char *string)
Prints the given string.
void print_int (const uint32_t number)
Prints the given integer.
void println (const char *string)
Prints the given string with a new line character.
void println_int (const uint32_t number)
Prints the given integer with a new line character.
void print_styled (const char *string, const Style *style)
Prints the given string with a predefined style.
void println_styled (const char *string, const Style *style)
Prints the given string with a predefined style and a new line character.
void printStyle (const Style *style)
Detailed Description
Author
Date
See also
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file print.c.
Function Documentation
print()
void print (const char * string)
Prints the given string.
Parameters
[in] string
Definition at line 30 of file print.c.
References uart_writeByte().
print_clearConsole()
void print_clearConsole ()
Clear the whole terminal.
Definition at line 25 of file print.c.
References CLEAR_SCREEN, and print().
print_int()
void print_int (const uint32_t number)
Prints the given integer.
Parameters
[in] number
Definition at line 39 of file print.c.
References int_to_str(), and print().
print_styled()
void print_styled (const char * string, const Style * style)
Prints the given string with a predefined style.
Parameters
[in] string
[in] style
Definition at line 58 of file print.c.
References print(), printStyle(), and RESET.
println()
void println (const char * string)
Prints the given string with a new line character.
Parameters
[in] string
Definition at line 46 of file print.c.
References LINE_SEPERATOR, print(), and uart_writeByte().
println_int()
void println_int (const uint32_t number)
Prints the given integer with a new line character.
Parameters
[in] number
Definition at line 52 of file print.c.
References LINE_SEPERATOR, print_int(), and uart_writeByte().
println_styled()
void println_styled (const char * string, const Style * style)
Prints the given string with a predefined style and a new line character.
Parameters
[in] string
[in] style
Definition at line 65 of file print.c.
References LINE_SEPERATOR, print_styled(), and uart_writeByte().
printStyle()
void printStyle (const Style * style)
Definition at line 71 of file print.c.
References Style::bg_color, Style::fg_color, Style::font_style, and print().