TikTakToe: logic/input.c File Reference
input.c File Reference
Implements input handling for the game.
#include "logic/input.h"
#include "config.h"
#include "logic/bot.h"
#include "logic/game.h"
#include "logic/time.h"
#include "logic/winning.h"
#include "presentation/cell.h"
#include "presentation/menu.h"
#include "presentation/style.h"
#include "presentation/ui.h"
#include "util/input_buf.h"
Functions
static void handleEscapeSequence (CellState *cell_state)
Handles escape sequences for navigation.
static void handleSetMark (GameState *game_state, CellState *cell_state)
Handles marking a cell during the game.
static void openControls ()
Opens the controls menu.
static bool handlePauseResume (CellState *cell_state)
Handles pausing and resuming the game.
bool input_handleByte (const uint8_t *byte, GameState *game_state, CellState *cell_state)
Handles an input byte and updates game and cell states.
Detailed Description
Implements input handling for the game.
See also
input.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file input.c.
Function Documentation
handleEscapeSequence()
static void handleEscapeSequence (CellState * cell_state) static
Handles escape sequences for navigation.
Processes escape sequences to move the selected cell up, down, left, or right based on arrow key input.
Parameters
[in,out] cell_state Pointer to the current cell state.
Definition at line 109 of file input.c.
References CellState::all, cell_state, CELLS_PER_COL, CELLS_PER_ROW, Cell::col, g_input_buf, input_getNext(), Cell::row, and CellState::selected.
handlePauseResume()
static bool handlePauseResume (CellState * cell_state) static
Handles pausing and resuming the game.
Toggles the game timer and redraws the cells as hidden when paused.
Parameters
[in,out] cell_state Pointer to the current cell state.
Returns
True if the game is resumed, false otherwise.
Definition at line 227 of file input.c.
References CellState::all, cell_redrawAll(), cell_state, g_timer, HIDDEN, GameTimer::is_running, time_pause(), and time_resume().
handleSetMark()
static void handleSetMark (GameState * game_state, CellState * cell_state) static
Handles marking a cell during the game.
Marks the currently selected cell based on the game mode and updates the game state. Handles special cases for player vs. computer (PVE) mode.
Parameters
[in,out] game_state Pointer to the current game state.
[in,out] cell_state Pointer to the current cell state.
Definition at line 155 of file input.c.
References CellState::all, bot_markRandomCell(), cell_redraw(), cell_select(), cell_state, CELLS_PER_COL, CELLS_PER_ROW, Circle, Cross, GameState::current_player, GameState::fields_marked, g_timer, game_endTurn(), game_state, GameTimer::is_running, CellState::last_circle, CellState::last_cross, Cell::marked_by, max, min, GameState::mode, None, PVE, GameState::round, CellState::selected, ui_updateTurn(), and winning_checkForWinner().
input_handleByte()
bool input_handleByte (const uint8_t * byte, GameState * game_state, CellState * cell_state)
Handles an input byte and updates game and cell states.
Processes the input byte to determine the appropriate action, such as marking a cell, navigating the board, or pausing the game. Updates the game state and cell state accordingly.
Parameters
[in] byte The input byte to process.
[in,out] game_state Pointer to the current game state.
[in,out] cell_state Pointer to the current cell state.
Returns
True if a field redraw is needed, false otherwise.
Definition at line 79 of file input.c.
References cell_decreaseSize(), cell_increaseSize(), cell_state, g_timer, game_state, handleEscapeSequence(), handlePauseResume(), handleSetMark(), GameTimer::is_running, and openControls().
openControls()
static void openControls () static
Opens the controls menu.
Displays the controls menu to the user. Pauses the game timer if it is running.
Definition at line 213 of file input.c.
References g_timer, GameTimer::is_running, menu_showControls(), time_pause(), and time_resume().