TikTakToe: presentation/cursor.c File Reference
cursor.c File Reference
Implements cursor movement functionality for the presentation layer.
#include "presentation/cursor.h"
#include "presentation/print.h"
#include "util/conversion.h"
Functions
static void writeNumToBuf (uint8_t num, const char *num_buf, char *buf, uint8_t *buf_pos)
Write a numeric value to a buffer.
void cursor_moveTo (const uint8_t x, const uint8_t y)
Move the cursor to the given coordinates.
Detailed Description
Implements cursor movement functionality for the presentation layer.
See also
cursor.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file cursor.c.
Function Documentation
cursor_moveTo()
void cursor_moveTo (uint8_t x, uint8_t y)
Move the cursor to the given coordinates.
This function generates an escape sequence to move the cursor to the specified (x, y) position on the terminal.
Parameters
[in] x X-coordinate of the cursor position.
[in] y Y-coordinate of the cursor position.
Note
This function can be improved by using new functions found in the conversion module and directly writing the string representation of the number to the target buffer.
Definition at line 34 of file cursor.c.
References int_to_str(), print(), and writeNumToBuf().
writeNumToBuf()
static void writeNumToBuf (uint8_t num, const char * num_buf, char * buf, uint8_t * buf_pos) static
Write a numeric value to a buffer.
This function writes the string representation of a numeric value to a buffer while maintaining the current position in the buffer.
Parameters
[in] num The numeric value to write.
[in] num_buf A buffer containing the string representation of the number.
[out] buf The target buffer to write to.
[in,out] buf_pos Pointer to the current position in the target buffer.
Definition at line 60 of file cursor.c.