TikTakToe: hal/timer.h File Reference
timer.h File Reference
Hardware Abstraction Layer
Contains constants and abstraction functions for the COUNTER device.
#include "def.h"
#include <stdint.h>
Macros
#define TIMER0_BASE_ADDRESS 0x40008000
#define TIMER1_BASE_ADDRESS 0x40009000
#define TIMER2_BASE_ADDRESS 0x4000A000
#define TIMER_START 0x000
#define TIMER_STOP 0x004
#define TIMER_COUNT 0x008
#define TIMER_CLEAR 0x00C
#define TIMER_SHUTDOWN 0x010
#define TIMER_CAPTURE_0 0x040
#define TIMER_CAPTURE_1 0x044
#define TIMER_CAPTURE_2 0x048
#define TIMER_CAPTURE_3 0x04C
#define TIMER_COMPARE_0 0x140
#define TIMER_COMPARE_1 0x144
#define TIMER_COMPARE_2 0x148
#define TIMER_COMPARE_3 0x14C
#define TIMER_SHORTS 0x200
#define TIMER_INTENSET 0x304
#define TIMER_INTENCLR 0x308
#define TIMER_MODE 0x504
#define TIMER_BITMODE 0x508
#define TIMER_PRESCALER 0x510
#define TIMER_CC_0 0x540
#define TIMER_CC_1 0x544
#define TIMER_CC_2 0x548
#define TIMER_CC_3 0x54C
#define TIMER_TASK_START 1
#define TIMER_EVENT_TRIGGER 1
#define TIMER_EVENT_CLEAR 0
#define SHORTS_COMPARE0_CLEAR_ENABLE (1 << 0)
#define SHORTS_COMPARE0_CLEAR_DISABLE (0 << 0)
#define SHORTS_COMPARE1_CLEAR_ENABLE (1 << 1)
#define SHORTS_COMPARE1_CLEAR_DISABLE (0 << 1)
#define SHORTS_COMPARE0_STOP_ENABLE (1 << 8)
#define SHORTS_COMPARE0_STOP_DISABLE (0 << 8)
#define SHORTS_COMPARE1_STOP_ENABLE (1 << 9)
#define SHORTS_COMPARE1_STOP_DISABLE (0 << 9)
#define INT_COMPARE0 (1 << 16)
#define INT_COMPARE1 (1 << 17)
#define INT_COMPARE2 (1 << 18)
#define INT_COMPARE3 (1 << 19)
Typedefs
typedef enum Timer Timer
typedef enum TimerBitMode TimerBitMode
typedef enum TimerCaptureCompare TimerCaptureCompare
Enumerations
enum Timer { TIMER0 , TIMER1 , TIMER2 }
enum TimerBitMode { TIMER_BIT_MODE_16 = 0 , TIMER_BIT_MODE_8 = 1 , TIMER_BIT_MODE_24 = 2 , TIMER_BIT_MODE_32 = 3 }
enum TimerCaptureCompare { CC0 , CC1 , CC2 , CC3 }
Functions
void timer_init (Timer timer)
Default Initialisation of Timer.
void timer_init_detailed (Timer timer, uint8_t prescaler, TimerBitMode bitMode)
Initialises the Timer.
void timer_captureCompareSet (Timer timer, TimerCaptureCompare captureCompare, uint32_t value, bool shortcutClear)
Set the Capture/ Compare Register of the Timer.
uint32_t timer_captureCompareGet (Timer timer, TimerCaptureCompare captureCompare)
Gets the Capture Compare Register of Timer.
void timer_start (Timer timer)
Starts the given timer.
void timer_stop (Timer timer)
Stops the given timer.
void timer_count (Timer timer)
Activate counting on the given timer.
void timer_clear (Timer timer)
Clear the time of the given timer.
void timer_capture (Timer timer, TimerCaptureCompare capture)
Capture the time of the given timer.
void timer_clearCompareEvent (Timer timer)
Clears the Compare Event for CC[0].
Detailed Description
Contains constants and abstraction functions for the COUNTER device.
Note
Based on version by Thomas Vogt
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file timer.h.
Macro Definition Documentation
INT_COMPARE0
#define INT_COMPARE0 (1 << 16)
Definition at line 74 of file timer.h.
INT_COMPARE1
#define INT_COMPARE1 (1 << 17)
Definition at line 75 of file timer.h.
INT_COMPARE2
#define INT_COMPARE2 (1 << 18)
Definition at line 76 of file timer.h.
INT_COMPARE3
#define INT_COMPARE3 (1 << 19)
Definition at line 77 of file timer.h.
SHORTS_COMPARE0_CLEAR_DISABLE
#define SHORTS_COMPARE0_CLEAR_DISABLE (0 << 0)
Definition at line 65 of file timer.h.
SHORTS_COMPARE0_CLEAR_ENABLE
#define SHORTS_COMPARE0_CLEAR_ENABLE (1 << 0)
Definition at line 64 of file timer.h.
SHORTS_COMPARE0_STOP_DISABLE
#define SHORTS_COMPARE0_STOP_DISABLE (0 << 8)
Definition at line 70 of file timer.h.
SHORTS_COMPARE0_STOP_ENABLE
#define SHORTS_COMPARE0_STOP_ENABLE (1 << 8)
Definition at line 69 of file timer.h.
SHORTS_COMPARE1_CLEAR_DISABLE
#define SHORTS_COMPARE1_CLEAR_DISABLE (0 << 1)
Definition at line 67 of file timer.h.
SHORTS_COMPARE1_CLEAR_ENABLE
#define SHORTS_COMPARE1_CLEAR_ENABLE (1 << 1)
Definition at line 66 of file timer.h.
SHORTS_COMPARE1_STOP_DISABLE
#define SHORTS_COMPARE1_STOP_DISABLE (0 << 9)
Definition at line 72 of file timer.h.
SHORTS_COMPARE1_STOP_ENABLE
#define SHORTS_COMPARE1_STOP_ENABLE (1 << 9)
Definition at line 71 of file timer.h.
TIMER0_BASE_ADDRESS
#define TIMER0_BASE_ADDRESS 0x40008000
Definition at line 24 of file timer.h.
TIMER1_BASE_ADDRESS
#define TIMER1_BASE_ADDRESS 0x40009000
Definition at line 25 of file timer.h.
TIMER2_BASE_ADDRESS
#define TIMER2_BASE_ADDRESS 0x4000A000
Definition at line 26 of file timer.h.
TIMER_BITMODE
#define TIMER_BITMODE 0x508
Definition at line 52 of file timer.h.
TIMER_CAPTURE_0
#define TIMER_CAPTURE_0 0x040
Definition at line 36 of file timer.h.
TIMER_CAPTURE_1
#define TIMER_CAPTURE_1 0x044
Definition at line 37 of file timer.h.
TIMER_CAPTURE_2
#define TIMER_CAPTURE_2 0x048
Definition at line 38 of file timer.h.
TIMER_CAPTURE_3
#define TIMER_CAPTURE_3 0x04C
Definition at line 39 of file timer.h.
TIMER_CC_0
#define TIMER_CC_0 0x540
Definition at line 54 of file timer.h.
TIMER_CC_1
#define TIMER_CC_1 0x544
Definition at line 55 of file timer.h.
TIMER_CC_2
#define TIMER_CC_2 0x548
Definition at line 56 of file timer.h.
TIMER_CC_3
#define TIMER_CC_3 0x54C
Definition at line 57 of file timer.h.
TIMER_CLEAR
#define TIMER_CLEAR 0x00C
Definition at line 33 of file timer.h.
TIMER_COMPARE_0
#define TIMER_COMPARE_0 0x140
Definition at line 42 of file timer.h.
TIMER_COMPARE_1
#define TIMER_COMPARE_1 0x144
Definition at line 43 of file timer.h.
TIMER_COMPARE_2
#define TIMER_COMPARE_2 0x148
Definition at line 44 of file timer.h.
TIMER_COMPARE_3
#define TIMER_COMPARE_3 0x14C
Definition at line 45 of file timer.h.
TIMER_COUNT
#define TIMER_COUNT 0x008
Definition at line 32 of file timer.h.
TIMER_EVENT_CLEAR
#define TIMER_EVENT_CLEAR 0
Definition at line 62 of file timer.h.
TIMER_EVENT_TRIGGER
#define TIMER_EVENT_TRIGGER 1
Definition at line 61 of file timer.h.
TIMER_INTENCLR
#define TIMER_INTENCLR 0x308
Definition at line 50 of file timer.h.
TIMER_INTENSET
#define TIMER_INTENSET 0x304
Definition at line 49 of file timer.h.
TIMER_MODE
#define TIMER_MODE 0x504
Definition at line 51 of file timer.h.
TIMER_PRESCALER
#define TIMER_PRESCALER 0x510
Definition at line 53 of file timer.h.
TIMER_SHORTS
#define TIMER_SHORTS 0x200
Definition at line 48 of file timer.h.
TIMER_SHUTDOWN
#define TIMER_SHUTDOWN 0x010
Definition at line 34 of file timer.h.
TIMER_START
#define TIMER_START 0x000
Definition at line 30 of file timer.h.
TIMER_STOP
#define TIMER_STOP 0x004
Definition at line 31 of file timer.h.
TIMER_TASK_START
#define TIMER_TASK_START 1
Definition at line 60 of file timer.h.
Typedef Documentation
Timer
typedef enum Timer Timer
TimerBitMode
typedef enum TimerBitMode TimerBitMode
TimerCaptureCompare
typedef enum TimerCaptureCompare TimerCaptureCompare
Enumeration Type Documentation
Timer
enum Timer
Enumerator
TIMER0
TIMER1
TIMER2
Definition at line 79 of file timer.h.
TimerBitMode
enum TimerBitMode
Enumerator
TIMER_BIT_MODE_16
TIMER_BIT_MODE_8
TIMER_BIT_MODE_24
TIMER_BIT_MODE_32
Definition at line 86 of file timer.h.
TimerCaptureCompare
enum TimerCaptureCompare
Enumerator
CC0
CC1
CC2
CC3
Definition at line 94 of file timer.h.
Function Documentation
timer_capture()
void timer_capture (Timer timer, TimerCaptureCompare capture)
Capture the time of the given timer.
Parameters
[in] timer Number of the timer
[in] capture Number of the Capture Compare
Definition at line 120 of file timer.c.
References register_write(), TIMER_TASK_START, TimerBase, and TimerCaptureTaskOffset.
timer_captureCompareGet()
uint32_t timer_captureCompareGet (Timer timer, TimerCaptureCompare captureCompare)
Gets the Capture Compare Register of Timer.
Parameters
timer Timer
captureCompare
Returns
Definition at line 84 of file timer.c.
References register_read(), TimerBase, and TimerCCOffset.
timer_captureCompareSet()
void timer_captureCompareSet (Timer timer, TimerCaptureCompare captureCompare, uint32_t value, bool shortcutClear)
Set the Capture/ Compare Register of the Timer.
It also enables the shortcut between CC[0] and CLEAR, so that the timer is cleared, when the compared value is reached.
Parameters
[in] timer Timer
[in] captureCompare Capture Compare Register
[in] value New Value
[in] shortcutClear
Definition at line 67 of file timer.c.
References register_read(), register_write(), TIMER_SHORTS, TimerBase, and TimerCCOffset.
timer_clear()
void timer_clear (Timer timer)
Clear the time of the given timer.
Parameters
[in] timer Number of the timer
Definition at line 113 of file timer.c.
References register_write(), TIMER_CLEAR, TIMER_TASK_START, and TimerBase.
timer_clearCompareEvent()
void timer_clearCompareEvent (Timer timer)
Clears the Compare Event for CC[0].
This could be useful for stopping the timer from pulling the interrupt-line.
Definition at line 128 of file timer.c.
References register_write(), TIMER_COMPARE_0, TIMER_EVENT_CLEAR, and TimerBase.
timer_count()
void timer_count (Timer timer)
Activate counting on the given timer.
Parameters
[in] timer Number of the timer
Definition at line 106 of file timer.c.
References register_write(), TIMER_COUNT, TIMER_TASK_START, and TimerBase.
timer_init()
void timer_init (Timer timer)
Default Initialisation of Timer.
Initializes the Timer Peripheral to a value ~4sek. This is just for demonstration and could be changed to your needs
Definition at line 40 of file timer.c.
References CC0, TIMER_BIT_MODE_32, timer_captureCompareSet(), timer_init_detailed(), and timer_start().
timer_init_detailed()
void timer_init_detailed (Timer timer, uint8_t prescaler, TimerBitMode bitMode)
Initialises the Timer.
Compare Value set is for CC[0]
Parameters
[in] prescaler Register value according to Table 147: PRESCALER. value 0..9 is valid ==> 2^0 .. 2^9
[in] bitmode Bit Mode.
Definition at line 48 of file timer.c.
References INT_COMPARE0, Interrupt_ID8, Interrupt_Set_Enable, register_write(), TIMER0_BASE_ADDRESS, TIMER_BITMODE, TIMER_INTENSET, TIMER_PRESCALER, and TimerBase.
timer_start()
void timer_start (Timer timer)
Starts the given timer.
Parameters
[in] timer Timer
Definition at line 92 of file timer.c.
References register_write(), TIMER_START, TIMER_TASK_START, and TimerBase.
timer_stop()
void timer_stop (Timer timer)
Stops the given timer.
Parameters
[in] timer Number of the timer
Definition at line 99 of file timer.c.
References register_write(), TIMER_STOP, TIMER_TASK_START, and TimerBase.