TikTakToe: hal/random.c File Reference
random.c File Reference
Implementation of the RNG HAL for random number generation.
#include "hal/random.h"
#include "hal/register_access.h"
#include <stdint.h>
Functions
void rng_init ()
Enables the generation of random numbers.
uint8_t rng_getRandomValue_immediately ()
Get the Random Value from the generator immediately.
uint8_t rng_getRandomValue_waiting ()
Get the Random Value from the generator by polling and waiting.
Detailed Description
Implementation of the RNG HAL for random number generation.
See also
random.h
Note
Based on version by Thomas Vogt
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file random.c.
Function Documentation
rng_getRandomValue_immediately()
uint8_t rng_getRandomValue_immediately ()
Get the Random Value from the generator immediately.
The function does not wait for the next value to be generated. It reads the current value from the RNG peripheral.
Returns
uint8_t A random byte.
Definition at line 27 of file random.c.
References register_read(), RNG_BASE_ADDRESS, and RNG_VALUE.
rng_getRandomValue_waiting()
uint8_t rng_getRandomValue_waiting ()
Get the Random Value from the generator by polling and waiting.
This function blocks until the RNG peripheral indicates that a new random value is ready. It then retrieves and returns the random byte.
Returns
uint8_t A random byte.
Definition at line 36 of file random.c.
References register_read(), register_write(), RNG_BASE_ADDRESS, RNG_EVENT_CLEAR, rng_getRandomValue_immediately(), and RNG_VALRDY.
rng_init()
void rng_init ()
Enables the generation of random numbers.
Definition at line 21 of file random.c.
References register_write(), RNG_BASE_ADDRESS, RNG_START, and RNG_TASK_START.