TikTakToe: presentation/cell.h File Reference
cell.h File Reference
Presentation Layer
Contains functions and definitions for managing the presentation of cells.
#include "logic/game.h"
#include "presentation/field.h"
#include <stdint.h>
Data Structures
struct CellSize
Struct representing the dimensions of a cell.
Macros
#define NUM_OF_SIZES 3
Number of available cell sizes.
#define INITIAL_INDEX 1
Initial index for cell size.
#define INITIAL_WIDTH 8
Initial width of a cell.
#define INITIAL_HEIGHT 5
Initial height of a cell.
#define INITIAL_SIZE Medium
Initial size of a cell.
#define FIELD_HEIGHT (CELLS_PER_COL * g_cell_size.height)
Height of the field based on cell size.
Enumerations
enum Size { Small = 0 , Medium = 1 , Large = 2 }
Enum representing the available cell sizes.
Functions
void cell_redraw (const Cell *cell)
Redraws the given cell.
void cell_redraw_withModifier (const Cell *cell, const char *modifier)
Redraws the given cell with a modifier.
void cell_redrawAll (Cell all_cells[][CELLS_PER_ROW], const char *modifier)
Redraws the entire field of cells.
void cell_select (const Cell *cell)
Selects the given cell.
void cell_increaseSize ()
Increases the size of the cells.
void cell_decreaseSize ()
Decreases the size of the cells.
Variables
CellSize g_cell_size
Global variable representing the current cell size.
Detailed Description
Contains functions and definitions for managing the presentation of cells.
This file provides functions to redraw cells, manage cell selection, and adjust cell sizes. It also defines the CellSize struct and Size enum for handling cell dimensions.
See also
cell.c
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file cell.h.
Macro Definition Documentation
FIELD_HEIGHT
#define FIELD_HEIGHT (CELLS_PER_COL * g_cell_size.height)
Height of the field based on cell size.
Definition at line 33 of file cell.h.
INITIAL_HEIGHT
#define INITIAL_HEIGHT 5
Initial height of a cell.
Definition at line 31 of file cell.h.
INITIAL_INDEX
#define INITIAL_INDEX 1
Initial index for cell size.
Definition at line 29 of file cell.h.
INITIAL_SIZE
#define INITIAL_SIZE Medium
Initial size of a cell.
Definition at line 32 of file cell.h.
INITIAL_WIDTH
#define INITIAL_WIDTH 8
Initial width of a cell.
Definition at line 30 of file cell.h.
NUM_OF_SIZES
#define NUM_OF_SIZES 3
Number of available cell sizes.
Definition at line 28 of file cell.h.
Enumeration Type Documentation
Size
enum Size
Enum representing the available cell sizes.
Enumerator
Small
Small cell size.
Medium
Medium cell size.
Large
Large cell size.
Definition at line 39 of file cell.h.
Function Documentation
cell_decreaseSize()
void cell_decreaseSize ()
Decreases the size of the cells.
Definition at line 160 of file cell.c.
References g_cell_size, CellSize::height, CellSize::size, Small, VALID_SIZES, and CellSize::width.
cell_increaseSize()
void cell_increaseSize ()
Increases the size of the cells.
Definition at line 149 of file cell.c.
References g_cell_size, CellSize::height, Large, CellSize::size, VALID_SIZES, and CellSize::width.
cell_redraw()
void cell_redraw (const Cell * cell)
Redraws the given cell.
Parameters
[in] cell Cell to redraw.
Definition at line 101 of file cell.c.
References Cell::col, Cell::marked_by, redrawCell(), and Cell::row.
cell_redraw_withModifier()
void cell_redraw_withModifier (const Cell * cell, const char * modifier)
Redraws the given cell with a modifier.
Parameters
[in] cell Cell to redraw.
[in] modifier Modifier to apply during redraw.
Definition at line 106 of file cell.c.
References Cell::col, Cell::marked_by, redrawCell(), and Cell::row.
cell_redrawAll()
void cell_redrawAll (Cell all_cells[][CELLS_PER_ROW], const char * modifier)
Redraws the entire field of cells.
Parameters
[in] all_cells 2D array of cells representing the field.
[in] modifier Modifier to apply during redraw.
Definition at line 136 of file cell.c.
References CELLS_PER_COL, CELLS_PER_ROW, Cell::col, Cell::marked_by, redrawCell(), and Cell::row.
cell_select()
void cell_select (const Cell * cell)
Selects the given cell.
Parameters
[in] cell Cell to select.
Definition at line 111 of file cell.c.
References Cell::col, INVERSE, Cell::marked_by, redrawCell(), and Cell::row.
Variable Documentation
g_cell_size
CellSize g_cell_size extern
Global variable representing the current cell size.
Initialized with default values for size, height, and width.
See also
VALID_SIZES
INITIAL_SIZE
INITIAL_HEIGHT
INITIAL_WIDTH
Definition at line 22 of file cell.c.