TikTakToe: presentation/print.h File Reference
print.h File Reference
Presentation Layer
Contains several different high level functions for printing to UART.
#include "presentation/style.h"
#include <stdint.h>
Macros
#define LINE_SEPERATOR '\n'
Functions
void print_clearConsole ()
Clear the whole terminal.
void print (const char *string)
Prints the given string.
void print_int (const uint32_t number)
Prints the given integer.
void println (const char *string)
Prints the given string with a new line character.
void println_int (const uint32_t number)
Prints the given integer with a new line character.
void print_styled (const char *string, const Style *style)
Prints the given string with a predefined style.
void println_styled (const char *string, const Style *style)
Prints the given string with a predefined style and a new line character.
void print_style (const Style *style)
Prints the given style attributes.
Detailed Description
Contains several different high level functions for printing to UART.
This file contains functions for printing strings, integers, and styled text to the UART interface. It also includes utility functions for clearing the console.
See also
print.c
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file print.h.
Macro Definition Documentation
LINE_SEPERATOR
#define LINE_SEPERATOR '\n'
Definition at line 26 of file print.h.
Function Documentation
print()
void print (const char * string)
Prints the given string.
Parameters
[in] string The string to print
Definition at line 25 of file print.c.
References uart_writeByte().
print_clearConsole()
void print_clearConsole ()
Clear the whole terminal.
Definition at line 20 of file print.c.
References CLEAR_SCREEN, and print().
print_int()
void print_int (const uint32_t number)
Prints the given integer.
Parameters
[in] number The integer to print
Definition at line 34 of file print.c.
References int_to_str(), and print().
print_style()
void print_style (const Style * style)
Prints the given style attributes.
Parameters
[in] style The style to print
Definition at line 66 of file print.c.
References Style::bg_color, Style::fg_color, Style::font_style, and print().
print_styled()
void print_styled (const char * string, const Style * style)
Prints the given string with a predefined style.
Parameters
[in] string The string to print
[in] style The style to apply
Definition at line 53 of file print.c.
References print(), print_style(), and RESET.
println()
void println (const char * string)
Prints the given string with a new line character.
Parameters
[in] string The string to print
Definition at line 41 of file print.c.
References LINE_SEPERATOR, print(), and uart_writeByte().
println_int()
void println_int (const uint32_t number)
Prints the given integer with a new line character.
Parameters
[in] number The integer to print
Definition at line 47 of file print.c.
References LINE_SEPERATOR, print_int(), and uart_writeByte().
println_styled()
void println_styled (const char * string, const Style * style)
Prints the given string with a predefined style and a new line character.
Parameters
[in] string The string to print
[in] style The style to apply
Definition at line 60 of file print.c.
References LINE_SEPERATOR, print_styled(), and uart_writeByte().