TikTakToe: presentation/menu.c File Reference
menu.c File Reference
Implements menu presentation functions.
#include "presentation/menu.h"
#include "config.h"
#include "hal/nvic.h"
#include "logic/game.h"
#include "presentation/ascii_art.h"
#include "presentation/cell.h"
#include "presentation/cursor.h"
#include "presentation/print.h"
#include "presentation/style.h"
#include "presentation/ui.h"
#include "util/input_buf.h"
Functions
static void printWinnerBanner (const GameState *game_info)
Prints the winner banner based on the game state.
static void printMainMenu ()
Prints the main menu options to the console.
bool menu_showMainMenu ()
Displays the main menu and handles user input.
void menu_showGameOver (const GameState *game_info)
Displays the game over screen and game summary.
void menu_showCredits ()
Displays the credits screen.
void menu_showControls (const char *continue_hint)
Displays the controls menu.
void menu_anyKeyToContinue (const char *continue_hint)
Waits for any key press to continue.
Detailed Description
Implements menu presentation functions.
See also
menu.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file menu.c.
Function Documentation
menu_anyKeyToContinue()
void menu_anyKeyToContinue (const char * continue_hint)
Waits for any key press to continue.
Parameters
[in] continue_hint Hint message displayed to prompt the user.
Definition at line 222 of file menu.c.
References __WFI, g_input_buf, input_getNext(), ITALIC_DIM, and println_styled().
menu_showControls()
void menu_showControls (const char * continue_hint)
Displays the controls menu.
Parameters
[in] continue_hint Hint message displayed to return to the menu.
Definition at line 174 of file menu.c.
References ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, BOLD_CROSS, DEFAULT_BOLD, ITALIC_DIM, menu_anyKeyToContinue(), print(), print_clearConsole(), print_styled(), println(), println_styled(), and ui_printHeading().
menu_showCredits()
void menu_showCredits ()
Displays the credits screen.
Definition at line 143 of file menu.c.
References BOLD_CROSS, DEFAULT_BOLD, ITALIC_DIM, menu_anyKeyToContinue(), print_clearConsole(), print_styled(), println(), println_styled(), RETURN_MENU_HINT, and ui_printHeading().
menu_showGameOver()
void menu_showGameOver (const GameState * game_info)
Displays the game over screen and game summary.
Parameters
[in] game_info Pointer to the game state containing game statistics.
Definition at line 86 of file menu.c.
References GameState::average_ticks, BOLD_CIRCLE, BOLD_CROSS, CELLS_PER_COL, GameState::circle_average_ticks, GameState::circle_total_ticks, GameState::cross_average_ticks, GameState::cross_total_ticks, cursor_moveTo(), DEFAULT_BOLD, DEFAULT_ITALIC, ERASE_LINE_FROM_CURSOR, GameState::fields_marked, g_cell_size, HEADING_LINES, CellSize::height, menu_anyKeyToContinue(), print(), print_clearConsole(), print_styled(), println_int(), println_styled(), printWinnerBanner(), RESET, RETURN_MENU_HINT, GameState::round, GameState::total_ticks, ui_gameOver(), and ui_printHeading().
menu_showMainMenu()
bool menu_showMainMenu ()
Displays the main menu and handles user input.
Returns
true if the game should reset, false if the game should quit.
Definition at line 42 of file menu.c.
References __WFI, g_input_buf, game_run(), HIDE_CURSOR, input_getNext(), menu_showControls(), menu_showCredits(), print(), printMainMenu(), PVE, PVP, and RETURN_MENU_HINT.
printMainMenu()
static void printMainMenu () static
Prints the main menu options to the console.
Definition at line 234 of file menu.c.
References DEFAULT_BOLD, DIM, ITALIC_DIM, print(), print_clearConsole(), println(), println_styled(), RESET, and ui_printHeading().
printWinnerBanner()
static void printWinnerBanner (const GameState * game_info) static
Prints the winner banner based on the game state.
Parameters
[in] game_info Pointer to the game state containing the winner information.
Definition at line 253 of file menu.c.
References BOLD_CIRCLE, BOLD_CROSS, BOLD_DIM, Circle, CIRCLE_WINS, Cross, CROSS_WINS, ITS_A_TIE, None, print_styled(), and GameState::winner.