TikTakToe: presentation/ui.h File Reference
ui.h File Reference
Presentation Layer
Contains different functions for the presentation of the in-game user interface (everything besides the actual game field).
#include "logic/game.h"
#include "presentation/ascii_art.h"
#include "presentation/cell.h"
#include <stdint.h>
Macros
#define TURN_ROW 1 + HEADING_LINES
Row position for displaying the turn text.
#define TIMER_ROW FIELD_HEIGHT + (FIELD_HEIGHT % 2) - 1 + HEADING_LINES
Row position for displaying the timer.
#define FULL_PROGRESS_ELEMENT "-"
Full progress bar element.
#define HALF_PROGRESS_ELEMENT "_"
Half progress bar element.
#define EMPTY_PROGRESS_ELEMENT ""
Empty progress bar element.
Functions
void ui_displayTimer (uint16_t remaining_time, uint16_t total_time)
Writes the timer text to the screen.
void ui_updateTimer (uint16_t remaining_time, uint16_t total_time)
Updates the time on the screen.
void ui_displayTurn (uint8_t current_turn, Player player)
Writes the turn text to the screen.
void ui_updateTurn (uint8_t current_turn, Player player)
Updates the turn number on the screen.
void ui_printStartingPlayer (Player starting_player, Mode mode)
Displays the starting player and mode.
void ui_printHeading ()
Prints the game heading to the screen.
void ui_gameOver ()
Displays the "Game Over" message on the screen.
Detailed Description
Contains different functions for the presentation of the in-game user interface (everything besides the actual game field).
This file provides functions to display and update the timer, turn text, and other UI elements for the game. It also includes macros for rendering progress elements and constants for positioning UI elements.
See also
ui.c
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file ui.h.
Macro Definition Documentation
EMPTY_PROGRESS_ELEMENT
#define EMPTY_PROGRESS_ELEMENT ""
Empty progress bar element.
Definition at line 41 of file ui.h.
FULL_PROGRESS_ELEMENT
#define FULL_PROGRESS_ELEMENT "-"
Full progress bar element.
Definition at line 39 of file ui.h.
HALF_PROGRESS_ELEMENT
#define HALF_PROGRESS_ELEMENT "_"
Half progress bar element.
Definition at line 40 of file ui.h.
TIMER_ROW
#define TIMER_ROW FIELD_HEIGHT + (FIELD_HEIGHT % 2) - 1 + HEADING_LINES
Row position for displaying the timer.
Definition at line 31 of file ui.h.
TURN_ROW
#define TURN_ROW 1 + HEADING_LINES
Row position for displaying the turn text.
Definition at line 30 of file ui.h.
Function Documentation
ui_displayTimer()
void ui_displayTimer (uint16_t remaining_time, uint16_t total_time)
Writes the timer text to the screen.
Parameters
[in] remaining_time The remaining time in seconds.
[in] total_time The total time in seconds.
Definition at line 24 of file ui.c.
References cursor_moveTo(), ITALIC_DIM, print(), print_styled(), TIMER_ROW, and ui_updateTimer().
ui_displayTurn()
void ui_displayTurn (uint8_t current_turn, Player player)
Writes the turn text to the screen.
Parameters
[in] current_turn The current turn number.
[in] player The player whose turn it is (Circle or Cross).
Definition at line 86 of file ui.c.
References cursor_moveTo(), DEFAULT_BOLD, DEFAULT_ITALIC, print_styled(), TURN_ROW, and ui_updateTurn().
ui_gameOver()
void ui_gameOver ()
Displays the "Game Over" message on the screen.
Definition at line 114 of file ui.c.
References cursor_moveTo(), DEFAULT_BOLD, ERASE_LINE_FROM_CURSOR, print(), print_styled(), TIMER_ROW, and TURN_ROW.
ui_printHeading()
void ui_printHeading ()
Prints the game heading to the screen.
Definition at line 124 of file ui.c.
References cursor_moveTo(), HEADING, HEADING_STYLE, and print_styled().
ui_printStartingPlayer()
void ui_printStartingPlayer (Player starting_player, Mode mode)
Displays the starting player and mode.
Parameters
[in] starting_player The player who starts the game.
[in] mode The game mode (e.g., PVE or PVP).
Definition at line 130 of file ui.c.
References BOLD, Circle, CIRCLE_STARTS, COMPUTER_STARTS, Cross, CROSS_STARTS, DEFAULT_CIRCLE, DEFAULT_CROSS, FG_RED, menu_anyKeyToContinue(), None, PLAYER_STARTS, print_clearConsole(), print_styled(), PVE, and ui_printHeading().
ui_updateTimer()
void ui_updateTimer (uint16_t remaining_time, uint16_t total_time)
Updates the time on the screen.
Parameters
[in] remaining_time The remaining time in seconds.
[in] total_time The total time in seconds.
Definition at line 34 of file ui.c.
References BOLD, cursor_moveTo(), DIM, EMPTY_PROGRESS_ELEMENT, ERASE_LINE_FROM_CURSOR, FG_GREEN, FG_RED, FG_YELLOW, FULL_PROGRESS_ELEMENT, g_timer, HALF_PROGRESS_ELEMENT, GameTimer::is_running, ITALIC_DIM, print(), print_styled(), println_styled(), TIMER_ROW, and uart_writeByte().
ui_updateTurn()
void ui_updateTurn (uint8_t current_turn, Player player)
Updates the turn number on the screen.
Parameters
[in] current_turn The current turn number.
[in] player The player whose turn it is (Circle or Cross).
Definition at line 96 of file ui.c.
References BOLD_CIRCLE, BOLD_CROSS, Circle, Cross, cursor_moveTo(), FG_GREEN, FG_MAGENTA, print(), print_int(), print_styled(), and TURN_ROW.