TikTakToe: logic/game.h File Reference
game.h File Reference
Logic Layer
Contains the game logic.
#include "presentation/field.h"
#include "util/input_buf.h"
#include <stdint.h>
Data Structures
struct Cell
One cell on the field.
struct GameState
The current game state.
struct CellState
The current state of the cells.
Macros
#define REMAINING_TIME (TICKS_PER_TURN - g_timer.ticks_turn)
Remaining time for the current turn.
#define FIRST_ROUND 1
Constant representing the first round of the game.
Enumerations
enum Mode { PVE , PVP }
Possible game modes.
enum Player { Circle = 0 , Cross = 1 , None = 2 }
Enum describing a player.
Functions
void game_run (const Mode mode)
Start the main game.
void game_onTimeOut ()
Automatically end a turn in case the turn time is over.
void game_endTurn ()
Finish the current turn.
Detailed Description
Contains the game logic.
This file contains the core logic for the TikTakToe game, including game state management, player handling, and cell state tracking.
See also
game.c
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file game.h.
Macro Definition Documentation
FIRST_ROUND
#define FIRST_ROUND 1
Constant representing the first round of the game.
Definition at line 28 of file game.h.
REMAINING_TIME
#define REMAINING_TIME (TICKS_PER_TURN - g_timer.ticks_turn)
Remaining time for the current turn.
Definition at line 27 of file game.h.
Enumeration Type Documentation
Mode
enum Mode
Possible game modes.
The game can be played in Player vs Computer (PVE) or Player vs Player (PVP) mode.
Enumerator
PVE
Player vs Computer.
PVP
Player vs Player.
Definition at line 35 of file game.h.
Player
enum Player
Enum describing a player.
Represents the two players (Circle and Cross) and an unmarked state (None).
Enumerator
Circle
Player Circle.
Cross
Player Cross.
None
No player (unmarked)
Definition at line 46 of file game.h.
Function Documentation
game_endTurn()
void game_endTurn ()
Finish the current turn.
Updates the game state and switches to the next player or round.
Definition at line 169 of file game.c.
References cell_state, Circle, Cross, GameState::current_player, GameState::fields_marked, game_state, CellState::last_circle, CellState::last_cross, GameState::mode, PVE, GameState::round, CellState::selected, and time_finishTurn().
game_onTimeOut()
void game_onTimeOut ()
Automatically end a turn in case the turn time is over.
See also
time_onInterrupt
Definition at line 149 of file game.c.
References CellState::all, bot_markRandomCell(), cell_state, Circle, Cross, GameState::current_player, force_ui_update, game_endTurn(), game_state, CellState::last_circle, CellState::last_cross, GameState::mode, and PVE.
game_run()
void game_run (const Mode mode)
Start the main game.
Initializes the game and enters the main game loop.
Parameters
[in] mode Which mode the game should be played in.
Definition at line 82 of file game.c.
References __WFI, CellState::all, BOLD, bot_markRandomCell(), calculateSummary(), cell_redraw_withModifier(), cell_redrawAll(), cell_select(), cell_state, CELLS_PER_COL, CELLS_PER_ROW, Circle, Cross, GameState::current_player, GameState::fields_marked, force_ui_update, g_input_buf, g_timer, game_state, handleForcedMoveUpdate(), init(), input_getNext(), input_handleByte(), GameTimer::is_running, CellState::last_circle, max, menu_showGameOver(), GameState::mode, None, PVE, redrawField(), REMAINING_TIME, GameState::round, CellState::selected, TICKS_PER_TURN, TIMER0, timer_stop(), ui_updateTimer(), ui_updateTurn(), GameState::winner, and winning_checkForWinner().