TikTakToe: presentation/field.c File Reference
field.c File Reference
Implements the rendering of the TikTakToe field.
#include "presentation/field.h"
#include "presentation/cell.h"
#include "presentation/cursor.h"
#include "presentation/print.h"
#include "config.h"
#include <stddef.h>
#include <stdint.h>
Functions
static void printRow (char **row, size_t row_length)
Print one row of the field.
void field_redraw ()
Redraw the whole 2D field.
Detailed Description
Implements the rendering of the TikTakToe field.
See also
field.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file field.c.
Function Documentation
field_redraw()
void field_redraw ()
Redraw the whole 2D field.
This function renders the entire tic-tac-toe field, including borders and empty cells, based on the current configuration.
Definition at line 35 of file field.c.
References CELLS_PER_COL, CELLS_PER_ROW, CORNER_BOT_LEFT, CORNER_BOT_RIGHT, CORNER_TOP_LEFT, CORNER_TOP_RIGHT, CROSS, cursor_moveTo(), EMPTY, FIELD_X_OFFSET, FIELD_Y_OFFSET, g_cell_size, CellSize::height, printRow(), SIDE, T_BOT, T_LEFT, T_RIGHT, T_TOP, TOP_BOTTOM, and CellSize::width.
printRow()
static void printRow (char ** row, size_t row_length) static
Print one row of the field.
Parameters
[in] row Array of strings representing the row to print.
[in] row_length Length of the row array.
Definition at line 98 of file field.c.
References print().