TikTakToe: hal/uart.h File Reference
uart.h File Reference
Hardware Abstraction Layer
Contains constants and abstraction functions for the UART device.
#include "def.h"
#include <stdint.h>
Macros
#define UART_BASE_ADDRESS 0x40002000
Base address for UART registers.
#define UART_STARTRX 0x000
Start UART receiver.
#define UART_STOPRX 0x004
Stop UART receiver.
#define UART_STARTTX 0x008
Start UART transmitter.
#define UART_STOPTX 0x00C
Stop UART transmitter.
#define UART_SUSPEND 0x01C
Suspend UART.
#define UART_CTS 0x100
CTS is activated (set low). Clear To Send.
#define UART_NCTS 0x104
CTS is deactivated (set high). Not Clear To Send.
#define UART_RXDRDY 0x108
Data received in RXD.
#define UART_TXDRDY 0x11C
Data sent from TXD.
#define UART_ERROR 0x124
Error detected.
#define UART_RXTO 0x144
Receiver timeout.
#define UART_INTEN 0x300
Enable or disable interrupt.
#define UART_INTENSET 0x304
Enable interrupt.
#define UART_INTENCLR 0x308
Disable interrupt.
#define UART_ERRORSRC 0x480
Error source.
#define UART_ENABLE 0x500
Enable UART.
#define UART_PSELRTS 0x508
Pin select for RTS.
#define UART_PSELTXD 0x50C
Pin select for TXD.
#define UART_PSELCTS 0x510
Pin select for CTS.
#define UART_PSELRXD 0x514
Pin select for RXD.
#define UART_RXD 0x518
RXD register.
#define UART_TXD 0x51C
TXD register.
#define UART_BAUDRATE 0x524
Baud rate.
#define UART_CONFIG 0x56C
Configuration of parity and hardware flow control.
#define UART_TASK_START 1
Value for starting a Task.
#define UART_EVENT_TRIGGER 1
Value for setting/starting an Event.
#define UART_EVENT_CLEAR 0
Value for clearing/stopping an Event.
#define UART_INT_RXDRDY (1 << 2)
Interrupt bit for RXDRDY event.
Functions
void uart_init (bool with_interrupts)
Initializes the UART with the following settings: 115200-8-N-1.
void uart_writeByte (uint8_t data)
Writes/Sends a byte over the serial port.
uint8_t uart_readByte ()
Reads/Receives a byte from the serial port.
Detailed Description
Contains constants and abstraction functions for the UART device.
This file provides macros for UART register offsets, tasks, events, and other configurations. It also declares functions for initializing the UART, sending, and receiving data.
See also
uart.c
Note
Based on version by Thomas Vogt
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file uart.h.
Macro Definition Documentation
UART_BASE_ADDRESS
#define UART_BASE_ADDRESS 0x40002000
Base address for UART registers.
Definition at line 31 of file uart.h.
UART_BAUDRATE
#define UART_BAUDRATE 0x524
Baud rate.
Definition at line 61 of file uart.h.
UART_CONFIG
#define UART_CONFIG 0x56C
Configuration of parity and hardware flow control.
Definition at line 62 of file uart.h.
UART_CTS
#define UART_CTS 0x100
CTS is activated (set low). Clear To Send.
Definition at line 42 of file uart.h.
UART_ENABLE
#define UART_ENABLE 0x500
Enable UART.
Definition at line 54 of file uart.h.
UART_ERROR
#define UART_ERROR 0x124
Error detected.
Definition at line 46 of file uart.h.
UART_ERRORSRC
#define UART_ERRORSRC 0x480
Error source.
Definition at line 53 of file uart.h.
UART_EVENT_CLEAR
#define UART_EVENT_CLEAR 0
Value for clearing/stopping an Event.
Definition at line 67 of file uart.h.
UART_EVENT_TRIGGER
#define UART_EVENT_TRIGGER 1
Value for setting/starting an Event.
Definition at line 66 of file uart.h.
UART_INT_RXDRDY
#define UART_INT_RXDRDY (1 << 2)
Interrupt bit for RXDRDY event.
Definition at line 69 of file uart.h.
UART_INTEN
#define UART_INTEN 0x300
Enable or disable interrupt.
Definition at line 50 of file uart.h.
UART_INTENCLR
#define UART_INTENCLR 0x308
Disable interrupt.
Definition at line 52 of file uart.h.
UART_INTENSET
#define UART_INTENSET 0x304
Enable interrupt.
Definition at line 51 of file uart.h.
UART_NCTS
#define UART_NCTS 0x104
CTS is deactivated (set high). Not Clear To Send.
Definition at line 43 of file uart.h.
UART_PSELCTS
#define UART_PSELCTS 0x510
Pin select for CTS.
Definition at line 57 of file uart.h.
UART_PSELRTS
#define UART_PSELRTS 0x508
Pin select for RTS.
Definition at line 55 of file uart.h.
UART_PSELRXD
#define UART_PSELRXD 0x514
Pin select for RXD.
Definition at line 58 of file uart.h.
UART_PSELTXD
#define UART_PSELTXD 0x50C
Pin select for TXD.
Definition at line 56 of file uart.h.
UART_RXD
#define UART_RXD 0x518
RXD register.
Definition at line 59 of file uart.h.
UART_RXDRDY
#define UART_RXDRDY 0x108
Data received in RXD.
Definition at line 44 of file uart.h.
UART_RXTO
#define UART_RXTO 0x144
Receiver timeout.
Definition at line 47 of file uart.h.
UART_STARTRX
#define UART_STARTRX 0x000
Start UART receiver.
Definition at line 35 of file uart.h.
UART_STARTTX
#define UART_STARTTX 0x008
Start UART transmitter.
Definition at line 37 of file uart.h.
UART_STOPRX
#define UART_STOPRX 0x004
Stop UART receiver.
Definition at line 36 of file uart.h.
UART_STOPTX
#define UART_STOPTX 0x00C
Stop UART transmitter.
Definition at line 38 of file uart.h.
UART_SUSPEND
#define UART_SUSPEND 0x01C
Suspend UART.
Definition at line 39 of file uart.h.
UART_TASK_START
#define UART_TASK_START 1
Value for starting a Task.
Definition at line 65 of file uart.h.
UART_TXD
#define UART_TXD 0x51C
TXD register.
Definition at line 60 of file uart.h.
UART_TXDRDY
#define UART_TXDRDY 0x11C
Data sent from TXD.
Definition at line 45 of file uart.h.
Function Documentation
uart_init()
void uart_init (bool with_interrupts)
Initializes the UART with the following settings: 115200-8-N-1.
Parameters
[in] with_interrupts Whether or not interrupts should be triggered.
Definition at line 20 of file uart.c.
References Interrupt_ID2, Interrupt_Set_Enable, register_write(), UART_BASE_ADDRESS, UART_ENABLE, UART_INT_RXDRDY, UART_INTENSET, UART_STARTRX, UART_STARTTX, and UART_TASK_START.
uart_readByte()
uint8_t uart_readByte ()
Reads/Receives a byte from the serial port.
Returns
uint8_t Received byte or 0 (zero) if nothing was received.
Definition at line 62 of file uart.c.
References register_read(), register_write(), UART_BASE_ADDRESS, UART_EVENT_CLEAR, UART_RXD, and UART_RXDRDY.
uart_writeByte()
void uart_writeByte (uint8_t data)
Writes/Sends a byte over the serial port.
Parameters
[in] data Byte to send.
Definition at line 54 of file uart.c.
References register_write(), UART_BASE_ADDRESS, and UART_TXD.