.TH "util Directory Reference" 3 "Sat Mar 22 2025 15:19:14" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconversion\&.c\fP"
.br
.RI "Implementation of utility functions for integer-to-string and integer-to-character conversions\&. "
.ti -1c
.RI "file \fBerror_handling\&.c\fP"
.br
.ti -1c
.RI "file \fBinput_buf\&.c\fP"
.br
.RI "Implementation of the input buffer functions\&. "
.in -1c
