.TH "hal Directory Reference" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.h\fP"
.br
.RI "Contains the relevant interrupt handlers\&. "
.ti -1c
.RI "file \fBmemset\&.h\fP"
.br
.RI "Header file for a simple implementation of memset\&. "
.ti -1c
.RI "file \fBnvic\&.h\fP"
.br
.RI "Contains interrupt constants\&. "
.ti -1c
.RI "file \fBrandom\&.h\fP"
.br
.RI "Header file for the RNG HAL\&. "
.ti -1c
.RI "file \fBregister_access\&.h\fP"
.br
.RI "Register Access Interface\&. "
.ti -1c
.RI "file \fBsystem\&.h\fP"
.br
.RI "System control interface for hardware abstraction layer\&. "
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.RI "Contains constants and abstraction functions for the COUNTER device\&. "
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.RI "Contains constants and abstraction functions for the UART device\&. "
.in -1c
