.TH "hal Directory Reference" 3 "Fri Mar 21 2025 12:43:06" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.c\fP"
.br
.ti -1c
.RI "file \fBmemset\&.c\fP"
.br
.ti -1c
.RI "file \fBrandom\&.c\fP"
.br
.ti -1c
.RI "file \fBregister_access\&.c\fP"
.br
.RI "Generic Register-Access\&. "
.ti -1c
.RI "file \fBsystem\&.c\fP"
.br
.ti -1c
.RI "file \fBtimer\&.c\fP"
.br
.ti -1c
.RI "file \fBuart\&.c\fP"
.br
.in -1c
