.TH "hal_low Directory Reference" 3 "Mon Mar 3 2025 08:06:03" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal_low Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.c\fP"
.br
.ti -1c
.RI "file \fBmemset\&.c\fP"
.br
.ti -1c
.RI "file \fBrandom\&.c\fP"
.br
.ti -1c
.RI "file \fBregister_access\&.c\fP"
.br
.RI "Generic Register-Access\&. "
.ti -1c
.RI "file \fBsystem\&.c\fP"
.br
.ti -1c
.RI "file \fBtimer\&.c\fP"
.br
.ti -1c
.RI "file \fBuart\&.c\fP"
.br
.in -1c
