.TH "logic Directory Reference" 3 "Sat Mar 22 2025 15:19:14" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbot\&.c\fP"
.br
.RI "Implementation of bot logic for Tic-Tac-Toe game\&. "
.ti -1c
.RI "file \fBgame\&.c\fP"
.br
.RI "Implements the core game logic for Tic-Tac-Toe\&. "
.ti -1c
.RI "file \fBinput\&.c\fP"
.br
.RI "Implements input handling for the game\&. "
.ti -1c
.RI "file \fBtime\&.c\fP"
.br
.RI "Implements time-related functionality for the game\&. "
.ti -1c
.RI "file \fBwinning\&.c\fP"
.br
.RI "Implements the function for checking if someone has won\&. "
.in -1c
