.TH "hal Directory Reference" 3 "Wed Mar 12 2025 14:12:43" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.h\fP"
.br
.RI "Contains interrupt handlers\&. "
.ti -1c
.RI "file \fBmemset\&.h\fP"
.br
.RI "Contains a simple implementation of memset\&. "
.ti -1c
.RI "file \fBnvic\&.h\fP"
.br
.RI "Contains interrupt constants\&. "
.ti -1c
.RI "file \fBrandom\&.h\fP"
.br
.RI "Contains constants and abstraction functions for the RNG device\&. "
.ti -1c
.RI "file \fBregister_access\&.h\fP"
.br
.RI "Contains abstraction functions of the register access\&. "
.ti -1c
.RI "file \fBsystem\&.h\fP"
.br
.RI "Contains functions interacting with the microcontroller\&. "
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.RI "Contains constants and abstraction functions for the COUNTER device\&. "
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.RI "Contains constants and abstraction functions for the UART device\&. "
.in -1c
