.TH "logic Directory Reference" 3 "Fri Mar 21 2025 12:44:01" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbot\&.c\fP"
.br
.ti -1c
.RI "file \fBgame\&.c\fP"
.br
.ti -1c
.RI "file \fBinput\&.c\fP"
.br
.ti -1c
.RI "file \fBtime\&.c\fP"
.br
.ti -1c
.RI "file \fBwinning\&.c\fP"
.br
.in -1c
