.TH "presentation Directory Reference" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcell\&.c\fP"
.br
.RI "Implements functions for managing the presentation of cells\&. "
.ti -1c
.RI "file \fBcursor\&.c\fP"
.br
.RI "Implements cursor movement functionality for the presentation layer\&. "
.ti -1c
.RI "file \fBfield\&.c\fP"
.br
.RI "Implements the rendering of the TikTakToe field\&. "
.ti -1c
.RI "file \fBmenu\&.c\fP"
.br
.RI "Implements menu presentation functions\&. "
.ti -1c
.RI "file \fBprint\&.c\fP"
.br
.RI "Implementation of high-level printing functions for UART\&. "
.ti -1c
.RI "file \fBstyle\&.c\fP"
.br
.RI "Implements predefined styles for terminal output\&. "
.ti -1c
.RI "file \fBui\&.c\fP"
.br
.RI "Implements functions for the in-game user interface\&. "
.in -1c
