.TH "presentation Directory Reference" 3 "Wed Mar 12 2025 14:09:10" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcell\&.c\fP"
.br
.ti -1c
.RI "file \fBcursor\&.c\fP"
.br
.ti -1c
.RI "file \fBfield\&.c\fP"
.br
.ti -1c
.RI "file \fBmenu\&.c\fP"
.br
.ti -1c
.RI "file \fBprint\&.c\fP"
.br
.ti -1c
.RI "file \fBstyle\&.c\fP"
.br
.ti -1c
.RI "file \fBui\&.c\fP"
.br
.in -1c
