.TH "presentation Directory Reference" 3 "Fri Mar 21 2025 12:09:51" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBascii_art\&.h\fP"
.br
.RI "Contains several ascii art constants\&. "
.ti -1c
.RI "file \fBcell\&.h\fP"
.br
.RI "Contains functions for changing the presentation of cells\&. "
.ti -1c
.RI "file \fBcursor\&.h\fP"
.br
.RI "Contains function for moving the presentation of the cursor\&. "
.ti -1c
.RI "file \fBfield\&.h\fP"
.br
.RI "Contains constants and one function to draw the whole field\&. "
.ti -1c
.RI "file \fBmenu\&.h\fP"
.br
.RI "Contains functions for presentation of the menu\&. "
.ti -1c
.RI "file \fBprint\&.h\fP"
.br
.RI "Contains several different high level functions for printing to UART\&. "
.ti -1c
.RI "file \fBstyle\&.h\fP"
.br
.RI "Contains several constants to simplify the styling of output\&. "
.ti -1c
.RI "file \fBui\&.h\fP"
.br
.RI "Contains different functions for the presentation of the in-game user interface (everything besides the actual game field) "
.in -1c
