.TH "logic Directory Reference" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbot\&.h\fP"
.br
.RI "Bot logic for Tic-Tac-Toe game\&. "
.ti -1c
.RI "file \fBgame\&.h\fP"
.br
.RI "Contains the game logic\&. "
.ti -1c
.RI "file \fBinput\&.h\fP"
.br
.RI "Contains the input handling of the game\&. "
.ti -1c
.RI "file \fBtime\&.h\fP"
.br
.RI "Contains time functions needed for the game\&. "
.ti -1c
.RI "file \fBwinning\&.h\fP"
.br
.RI "Contains the function for checking if someone has won\&. "
.in -1c
