.TH "hal Directory Reference" 3 "Mon Mar 3 2025 16:29:10" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.h\fP"
.br
.ti -1c
.RI "file \fBmemset\&.h\fP"
.br
.ti -1c
.RI "file \fBnvic\&.h\fP"
.br
.ti -1c
.RI "file \fBrandom\&.h\fP"
.br
.ti -1c
.RI "file \fBregister_access\&.h\fP"
.br
.ti -1c
.RI "file \fBsystem\&.h\fP"
.br
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.in -1c
