.TH "hal Directory Reference" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.c\fP"
.br
.RI "Implements the interrupt handlers for UART and Timer interrupts\&. "
.ti -1c
.RI "file \fBmemset\&.c\fP"
.br
.RI "Implementation of a simple memset function\&. "
.ti -1c
.RI "file \fBrandom\&.c\fP"
.br
.RI "Implementation of the RNG HAL for random number generation\&. "
.ti -1c
.RI "file \fBregister_access\&.c\fP"
.br
.RI "Register Access Implementation\&. "
.ti -1c
.RI "file \fBsystem\&.c\fP"
.br
.RI "Implementation of system control functions\&. "
.ti -1c
.RI "file \fBtimer\&.c\fP"
.br
.ti -1c
.RI "file \fBuart\&.c\fP"
.br
.RI "Implements UART initialization and data transfer functions\&. "
.in -1c
