.TH "presentation/ascii_art.h" 3 "Mon Mar 3 2025 16:55:31" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/ascii_art.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEADING_LINES\fP   3"
.br
.ti -1c
.RI "#define \fBHEADING\fP   '\\n TikTakToe \\n'"
.br
.ti -1c
.RI "#define \fBCROSS_WINS\fP   '\\n \fBCross\fP Wins! \\n'"
.br
.ti -1c
.RI "#define \fBCIRCLE_WINS\fP   '\\n \fBCircle\fP Wins! \\n'"
.br
.ti -1c
.RI "#define \fBITS_A_TIE\fP   '\\n It's a Tie! \\n'"
.br
.ti -1c
.RI "#define \fBPLAYER_STARTS\fP   '\\n \fBPlayer\fP starts! \\n'"
.br
.ti -1c
.RI "#define \fBCOMPUTER_STARTS\fP   '\\n Computer starts! \\n'"
.br
.ti -1c
.RI "#define \fBCIRCLE_STARTS\fP   '\\n \fBCircle\fP starts! \\n'"
.br
.ti -1c
.RI "#define \fBCROSS_STARTS\fP   '\\n \fBCross\fP starts! \\n'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CIRCLE_STARTS   '\\n \fBCircle\fP starts! \\n'"

.PP
Definition at line \fB112\fP of file \fBascii_art\&.h\fP\&.
.SS "#define CIRCLE_WINS   '\\n \fBCircle\fP Wins! \\n'"

.PP
Definition at line \fB104\fP of file \fBascii_art\&.h\fP\&.
.SS "#define COMPUTER_STARTS   '\\n Computer starts! \\n'"

.PP
Definition at line \fB110\fP of file \fBascii_art\&.h\fP\&.
.SS "#define CROSS_STARTS   '\\n \fBCross\fP starts! \\n'"

.PP
Definition at line \fB114\fP of file \fBascii_art\&.h\fP\&.
.SS "#define CROSS_WINS   '\\n \fBCross\fP Wins! \\n'"

.PP
Definition at line \fB102\fP of file \fBascii_art\&.h\fP\&.
.SS "#define HEADING   '\\n TikTakToe \\n'"

.PP
Definition at line \fB100\fP of file \fBascii_art\&.h\fP\&.
.SS "#define HEADING_LINES   3"

.PP
Definition at line \fB98\fP of file \fBascii_art\&.h\fP\&.
.SS "#define ITS_A_TIE   '\\n It's a Tie! \\n'"

.PP
Definition at line \fB106\fP of file \fBascii_art\&.h\fP\&.
.SS "#define PLAYER_STARTS   '\\n \fBPlayer\fP starts! \\n'"

.PP
Definition at line \fB108\fP of file \fBascii_art\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
