.TH "presentation/ascii_art.h" 3 "Mon Mar 3 2025 08:08:04" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/ascii_art.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEADING_LINES\fP   9"
.br
.ti -1c
.RI "#define \fBHEADING\fP       '\\\&.___________\&. __   __  ___ \&.___________\&.    ___       __  ___ \&.___________\&.  ______    _______  \\n\\|           ||  | |  |/  / |           |   /   \\\\     |  |/  / |           | /  __  \\\\  |   ____| \\n\\`\-\-\-|  |\-\-\-\-`|  | |  '  /  `\-\-\-|  |\-\-\-\-`  /  ^  \\\\    |  '  /  `\-\-\-|  |\-\-\-\-`|  |  |  | |  |__    \\n\\    |  |     |  | |    <       |  |      /  /_\\\\  \\\\   |    <       |  |     |  |  |  | |   __|   \\n\\    |  |     |  | |  \&.  \\\\      |  |     /  _____  \\\\  |  \&.  \\\\      |  |     |  `\-\-'  | |  |____  \\n\\    |__|     |__| |__|\\\\__\\\\     |__|    /__/     \\\\__\\\\ |__|\\\\__\\\\     |__|      \\\\______/  |_______| \\n\\_______________________________________________________________________________________________\\n\\'"
.br
.ti -1c
.RI "#define \fBCROSS_WINS\fP       '\\  ____                    __        ___           _ \\n\\ / ___|_ __ ___  ___ ___  \\\\ \\\\      / (_)_ __  ___| |\\n\\| |   | '__/ _ \\\\/ __/ __|  \\\\ \\\\ /\\\\ / /| | '_ \\\\/ __| |\\n\\| |___| | | (_) \\\\__ \\\\__ \\\\   \\\\ V  V / | | | | \\\\__ \\\\_|\\n\\ \\\\____|_|  \\\\___/|___/___/    \\\\_/\\\\_/  |_|_| |_|___(_)\\n\\'"
.br
.ti -1c
.RI "#define \fBCIRCLE_WINS\fP       '\\  ____ _          _       __        ___           _ \\n\\ / ___(_)_ __ ___| | ___  \\\\ \\\\      / (_)_ __  ___| |\\n\\| |   | | '__/ __| |/ _ \\\\  \\\\ \\\\ /\\\\ / /| | '_ \\\\/ __| |\\n\\| |___| | | | (__| |  __/   \\\\ V  V / | | | | \\\\__ \\\\_|\\n\\ \\\\____|_|_|  \\\\___|_|\\\\___|    \\\\_/\\\\_/  |_|_| |_|___(_)\\n\\'"
.br
.ti -1c
.RI "#define \fBITS_A_TIE\fP       '\\ ___ _   _               _____ _      _ \\n\\|_ _| |_( )___    __ _  |_   _(_) ___| |\\n\\ | || __|// __|  / _` |   | | | |/ _ \\\\ |\\n\\ | || |_  \\\\__ \\\\ | (_| |   | | | |  __/_|\\n\\|___|\\\\__| |___/  \\\\__,_|   |_| |_|\\\\___(_)\\n\\'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CIRCLE_WINS       '\\  ____ _          _       __        ___           _ \\n\\ / ___(_)_ __ ___| | ___  \\\\ \\\\      / (_)_ __  ___| |\\n\\| |   | | '__/ __| |/ _ \\\\  \\\\ \\\\ /\\\\ / /| | '_ \\\\/ __| |\\n\\| |___| | | | (__| |  __/   \\\\ V  V / | | | | \\\\__ \\\\_|\\n\\ \\\\____|_|_|  \\\\___|_|\\\\___|    \\\\_/\\\\_/  |_|_| |_|___(_)\\n\\'"

.PP
Definition at line \fB39\fP of file \fBascii_art\&.h\fP\&.
.SS "#define CROSS_WINS       '\\  ____                    __        ___           _ \\n\\ / ___|_ __ ___  ___ ___  \\\\ \\\\      / (_)_ __  ___| |\\n\\| |   | '__/ _ \\\\/ __/ __|  \\\\ \\\\ /\\\\ / /| | '_ \\\\/ __| |\\n\\| |___| | | (_) \\\\__ \\\\__ \\\\   \\\\ V  V / | | | | \\\\__ \\\\_|\\n\\ \\\\____|_|  \\\\___/|___/___/    \\\\_/\\\\_/  |_|_| |_|___(_)\\n\\'"

.PP
Definition at line \fB30\fP of file \fBascii_art\&.h\fP\&.
.SS "#define HEADING       '\\\&.___________\&. __   __  ___ \&.___________\&.    ___       __  ___ \&.___________\&.  ______    _______  \\n\\|           ||  | |  |/  / |           |   /   \\\\     |  |/  / |           | /  __  \\\\  |   ____| \\n\\`\-\-\-|  |\-\-\-\-`|  | |  '  /  `\-\-\-|  |\-\-\-\-`  /  ^  \\\\    |  '  /  `\-\-\-|  |\-\-\-\-`|  |  |  | |  |__    \\n\\    |  |     |  | |    <       |  |      /  /_\\\\  \\\\   |    <       |  |     |  |  |  | |   __|   \\n\\    |  |     |  | |  \&.  \\\\      |  |     /  _____  \\\\  |  \&.  \\\\      |  |     |  `\-\-'  | |  |____  \\n\\    |__|     |__| |__|\\\\__\\\\     |__|    /__/     \\\\__\\\\ |__|\\\\__\\\\     |__|      \\\\______/  |_______| \\n\\_______________________________________________________________________________________________\\n\\'"

.PP
Definition at line \fB18\fP of file \fBascii_art\&.h\fP\&.
.SS "#define HEADING_LINES   9"

.PP
Definition at line \fB4\fP of file \fBascii_art\&.h\fP\&.
.SS "#define ITS_A_TIE       '\\ ___ _   _               _____ _      _ \\n\\|_ _| |_( )___    __ _  |_   _(_) ___| |\\n\\ | || __|// __|  / _` |   | | | |/ _ \\\\ |\\n\\ | || |_  \\\\__ \\\\ | (_| |   | | | |  __/_|\\n\\|___|\\\\__| |___/  \\\\__,_|   |_| |_|\\\\___(_)\\n\\'"

.PP
Definition at line \fB48\fP of file \fBascii_art\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
