.TH "logic/bot.h" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/bot.h \- Bot logic for Tic-Tac-Toe game\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'logic/game\&.h'\fP
.br
\fR#include 'presentation/field\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCell\fP * \fBbot_markRandomCell\fP (\fBCell\fP cells[\fBCELLS_PER_COL\fP][\fBCELLS_PER_ROW\fP], \fBPlayer\fP marked_by)"
.br
.RI "Mark a random unmarked cell on the game board\&. "
.in -1c
.SH "Detailed Description"
.PP 
Bot logic for Tic-Tac-Toe game\&. 

This file contains the declaration of functions used to implement bot logic for the Tic-Tac-Toe game, such as marking a random cell\&.

.PP
\fBSee also\fP
.RS 4
\fBbot\&.c\fP \fBgame\&.h\fP \fBfield\&.h\fP
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBbot\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBCell\fP * bot_markRandomCell (\fBCell\fP cells[CELLS_PER_COL][CELLS_PER_ROW], \fBPlayer\fP marked_by)"

.PP
Mark a random unmarked cell on the game board\&. 
.PP
\fBParameters\fP
.RS 4
\fIcells\fP 2D field of cells representing the game board\&. 
.br
\fImarked_by\fP Player who should mark the cell\&.
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the marked cell\&.
.RE
.PP
\fBWarning\fP
.RS 4
This function assumes that there is at least one unmarked cell on the board\&. If there is not, the function will loop indefinitely\&. 
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBbot\&.c\fP\&.
.PP
References \fBCELLS_PER_COL\fP, \fBCELLS_PER_ROW\fP, \fBNone\fP, and \fBrng_getRandomValue_waiting()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
