.TH "Cell" 3 "Sat Mar 22 2025 15:19:14" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell \- One cell on the field\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcol\fP"
.br
.RI "Column index of the cell\&. "
.ti -1c
.RI "uint16_t \fBrow\fP"
.br
.RI "Row index of the cell\&. "
.ti -1c
.RI "\fBPlayer\fP \fBmarked_by\fP"
.br
.RI "Player who marked the cell\&. "
.in -1c
.SH "Detailed Description"
.PP 
One cell on the field\&. 

Contains coordinates and information about which player marked the cell\&. 
.PP
Definition at line \fB58\fP of file \fBgame\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t Cell::col"

.PP
Column index of the cell\&. 
.PP
Definition at line \fB60\fP of file \fBgame\&.h\fP\&.
.SS "\fBPlayer\fP Cell::marked_by"

.PP
Player who marked the cell\&. 
.PP
Definition at line \fB62\fP of file \fBgame\&.h\fP\&.
.SS "uint16_t Cell::row"

.PP
Row index of the cell\&. 
.PP
Definition at line \fB61\fP of file \fBgame\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
