.TH "Cell" 3 "Mon Mar 3 2025 08:08:04" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell \- One cell on the field\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcol\fP"
.br
.ti -1c
.RI "uint16_t \fBrow\fP"
.br
.ti -1c
.RI "\fBPlayer\fP \fBmarked_by\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One cell on the field\&. 

Contains coordinates and information by whom it is marked 
.PP
Definition at line \fB46\fP of file \fBgame\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t Cell::col"

.PP
Definition at line \fB48\fP of file \fBgame\&.h\fP\&.
.SS "\fBPlayer\fP Cell::marked_by"

.PP
Definition at line \fB50\fP of file \fBgame\&.h\fP\&.
.SS "uint16_t Cell::row"

.PP
Definition at line \fB49\fP of file \fBgame\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
