.TH "CellState" 3 "Mon Mar 3 2025 16:55:31" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CellState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCell\fP \fBall\fP [\fBCELLS_PER_COL\fP][\fBCELLS_PER_ROW\fP]"
.br
.ti -1c
.RI "\fBCell\fP * \fBselected\fP"
.br
.ti -1c
.RI "\fBCell\fP * \fBlast_cross\fP"
.br
.ti -1c
.RI "\fBCell\fP * \fBlast_circle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB72\fP of file \fBgame\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBCell\fP CellState::all[\fBCELLS_PER_COL\fP][\fBCELLS_PER_ROW\fP]"

.PP
Definition at line \fB74\fP of file \fBgame\&.h\fP\&.
.SS "\fBCell\fP* CellState::last_circle"

.PP
Definition at line \fB77\fP of file \fBgame\&.h\fP\&.
.SS "\fBCell\fP* CellState::last_cross"

.PP
Definition at line \fB76\fP of file \fBgame\&.h\fP\&.
.SS "\fBCell\fP* CellState::selected"

.PP
Definition at line \fB75\fP of file \fBgame\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
