.TH "config.h" 3 "Fri Mar 21 2025 12:20:37" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENABLE_UNICODE\fP"
.br
.ti -1c
.RI "#define \fBENABLE_ASCII_ART\fP"
.br
.ti -1c
.RI "#define \fBCELLS_PER_ROW\fP   4"
.br
.ti -1c
.RI "#define \fBCELLS_PER_COL\fP   4"
.br
.ti -1c
.RI "#define \fBTICKS_PER_TURN\fP   20"
.br
.ti -1c
.RI "#define \fBTICK_SPEED\fP   12"
.br
.in -1c
.SH "Detailed Description"
.PP 
!! This file has been generated automatically, any changes may be overridden !! !

.PP
\fBAuthor\fP
.RS 4
.RE
.PP
\fBDate\fP
.RS 4
.RE
.PP
\fBSee also\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBconfig\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CELLS_PER_COL   4"

.PP
Definition at line \fB28\fP of file \fBconfig\&.h\fP\&.
.SS "#define CELLS_PER_ROW   4"

.PP
Definition at line \fB27\fP of file \fBconfig\&.h\fP\&.
.SS "#define ENABLE_ASCII_ART"

.PP
Definition at line \fB24\fP of file \fBconfig\&.h\fP\&.
.SS "#define ENABLE_UNICODE"

.PP
Definition at line \fB22\fP of file \fBconfig\&.h\fP\&.
.SS "#define TICK_SPEED   12"

.PP
Definition at line \fB32\fP of file \fBconfig\&.h\fP\&.
.SS "#define TICKS_PER_TURN   20"

.PP
Definition at line \fB31\fP of file \fBconfig\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
