.TH "util/conversion.c" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/conversion.c \- Implementation of utility functions for integer-to-string and integer-to-character conversions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'util/conversion\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int8_t \fBint_to_str\fP (uint32_t num, char *buf, const size_t buf_size)"
.br
.RI "Converts an integer to a string\&. "
.ti -1c
.RI "char \fBint_to_char\fP (uint8_t num)"
.br
.RI "Converts an integer to a character\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of utility functions for integer-to-string and integer-to-character conversions\&. 


.PP
\fBSee also\fP
.RS 4
\fBconversion\&.h\fP
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBconversion\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "char int_to_char (uint8_t num)"

.PP
Converts an integer to a character\&. Converts a single-digit integer (0-9) to its corresponding ASCII character\&.

.PP
\fBParameters\fP
.RS 4
\fInum\fP The integer to convert (must be between 0 and 9)\&.
.RE
.PP
\fBReturns\fP
.RS 4
The ASCII character corresponding to the input integer\&. 
.RE
.PP

.PP
Definition at line \fB55\fP of file \fBconversion\&.c\fP\&.
.PP
References \fBASCII_NUM_OFFSET\fP\&.
.SS "int8_t int_to_str (uint32_t num, char * buf, const size_t buf_size)"

.PP
Converts an integer to a string\&. Converts a given unsigned integer to its string representation and stores it in the provided buffer\&.

.PP
\fBParameters\fP
.RS 4
\fInum\fP The integer to convert\&. 
.br
\fIbuf\fP The buffer to store the resulting string\&. 
.br
\fIbuf_size\fP The size of the buffer\&.
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 if an error occurred (e\&.g\&., buffer is NULL or too small)\&. 
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBconversion\&.c\fP\&.
.PP
References \fBASCII_NUM_OFFSET\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
