.TH "presentation/cursor.c" 3 "Fri Mar 21 2025 12:44:01" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/cursor.c
.SH SYNOPSIS
.br
.PP
\fR#include 'presentation/cursor\&.h'\fP
.br
\fR#include 'presentation/print\&.h'\fP
.br
\fR#include 'util/conversion\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBwriteNumToBuf\fP (uint8_t num, const char *num_buf, char *buf, uint8_t *buf_pos)"
.br
.RI "TODO: ????? "
.ti -1c
.RI "void \fBcursor_moveTo\fP (const uint8_t x, const uint8_t y)"
.br
.RI "Move cursor to the given coordinates\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4

.RE
.PP
\fBDate\fP
.RS 4
.RE
.PP
\fBSee also\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBcursor\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void cursor_moveTo (uint8_t x, uint8_t y)"

.PP
Move cursor to the given coordinates\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP X-Position 
.br
\fIy\fP Y-Position 
.RE
.PP

.PP
Definition at line \fB32\fP of file \fBcursor\&.c\fP\&.
.PP
References \fBint_to_str()\fP, \fBprint()\fP, and \fBwriteNumToBuf()\fP\&.
.SS "static void writeNumToBuf (uint8_t num, const char * num_buf, char * buf, uint8_t * buf_pos)\fR [static]\fP"

.PP
TODO: ????? 
.PP
\fBParameters\fP
.RS 4
\fInum\fP 
.br
\fInum_buf\fP 
.br
\fIbuf\fP 
.br
\fIbuf_pos\fP 
.RE
.PP

.PP
Definition at line \fB58\fP of file \fBcursor\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
