.TH "presentation/cursor.h" 3 "Wed Mar 12 2025 11:27:55" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/cursor.h \- Contains function for moving the presentation of the cursor\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcursor_moveTo\fP (uint8_t x, uint8_t y)"
.br
.RI "Move cursor to the given coordinates\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains function for moving the presentation of the cursor\&. 


.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBcursor\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void cursor_moveTo (uint8_t x, uint8_t y)"

.PP
Move cursor to the given coordinates\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP X-Position 
.br
\fIy\fP Y-Position 
.RE
.PP

.PP
Definition at line \fB32\fP of file \fBcursor\&.c\fP\&.
.PP
References \fBint_to_str()\fP, \fBprint()\fP, and \fBwriteNumToBuf()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
