.TH "def.h" 3 "Mon Mar 3 2025 08:06:03" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
def.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBbool\fP   char"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4

.RE
.PP
\fBDate\fP
.RS 4
.RE
.PP
\fBSee also\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBdef\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define bool   char"

.PP
Definition at line \fB20\fP of file \fBdef\&.h\fP\&.
.SS "#define false   0"

.PP
Definition at line \fB21\fP of file \fBdef\&.h\fP\&.
.SS "#define true   1"

.PP
Definition at line \fB22\fP of file \fBdef\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
