.TH "/github/workspace/entry/entry.S" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/github/workspace/entry/entry.S \- Entry point and initialization routines for the Tic-Tac-Toe project\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Entry point and initialization routines for the Tic-Tac-Toe project\&. 

This file contains the interrupt vector table, reset handler, and initialization routines for the Cortex-M0 processor\&. It also includes default handlers for interrupts and exceptions\&.

.PP
\fBNote\fP
.RS 4
This file is written in ARM assembly and is intended to be processed by the \fRasm4doxy\&.pl\fP script for generating Doxygen-compatible documentation\&. Generated documentation can be found under the file \fR\fBentry-S\&.c\fP\fP
.RE
.PP
\fBSee also\fP
.RS 4
\fBentry-S\&.c\fP
.RE
.PP
\fBNote\fP
.RS 4
Based on version by Thomas Vogt and Sven Reis
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBentry\&.S\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
