.TH "/home/simon/2_Uni/tiktaktoe/entry/entry.doc.c" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/simon/2_Uni/tiktaktoe/entry/entry.doc.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDefault_Handler\fP (void)"
.br
.RI "Handles unexpected interrupts\&. "
.ti -1c
.RI "void \fBHardFault_Handler\fP (void)"
.br
.RI "Default HardFault handler\&. "
.ti -1c
.RI "void \fBReset_Handler\fP (void)"
.br
.RI "Reset handler\&. "
.ti -1c
.RI "void \fBcopyData\fP (void)"
.br
.RI "Copies the \fR\&.data\fP section from flash to RAM\&. "
.ti -1c
.RI "void \fBg_pfnVectors\fP (void)"
.br
.RI "Interrupt vector table\&. "
.ti -1c
.RI "void \fBzeroBss\fP (void)"
.br
.RI "Zeroes the \fR\&.bss\fP section\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void copyData (void)"

.PP
Copies the \fR\&.data\fP section from flash to RAM\&. This function initializes the \fR\&.data\fP section by copying its contents from the load address in flash to the execution address in RAM\&. 
.PP
Definition at line \fB97\fP of file \fBentry\&.doc\&.c\fP\&.
.SS "void Default_Handler (void)"

.PP
Handles unexpected interrupts\&. This function is triggered when an unexpected interrupt occurs\&. It provides a mechanism to handle the interrupt and display an appropriate message\&.
.PP
Handles unexpected interrupts\&.
.PP
This is a weak symbol that can be overridden by a user-defined handler\&. 
.PP
Definition at line \fB44\fP of file \fBentry\&.doc\&.c\fP\&.
.SS "void g_pfnVectors (void)"

.PP
Interrupt vector table\&. This table defines the initial stack pointer and the entry points for various exceptions and interrupts\&. 
.PP
Definition at line \fB109\fP of file \fBentry\&.doc\&.c\fP\&.
.SS "void HardFault_Handler (void)"

.PP
Default HardFault handler\&. Handles hard faults\&.
.PP
This is a weak symbol that can be overridden by a user-defined handler\&. 
.PP
Definition at line \fB73\fP of file \fBentry\&.doc\&.c\fP\&.
.SS "void Reset_Handler (void)"

.PP
Reset handler\&. This function is the entry point after a reset\&. It initializes the \fR\&.bss\fP and \fR\&.data\fP sections and then calls the \fRmain\fP function\&. 
.PP
Definition at line \fB85\fP of file \fBentry\&.doc\&.c\fP\&.
.SS "void zeroBss (void)"

.PP
Zeroes the \fR\&.bss\fP section\&. This function sets all bytes in the \fR\&.bss\fP section to zero\&. 
.PP
Definition at line \fB120\fP of file \fBentry\&.doc\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
