.TH "util/error_handling.h" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/error_handling.h \- Contains functions to react on errors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHardFault_Handler\fP () __attribute__((interrupt))"
.br
.RI "Handles hard faults\&. "
.ti -1c
.RI "void \fBDefault_Handler\fP () __attribute__((interrupt))"
.br
.RI "Handles unexpected interrupts\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains functions to react on errors\&. 


.PP
\fBSee also\fP
.RS 4
\fBerror_handling\&.c\fP
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBerror_handling\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Default_Handler (void )"

.PP
Handles unexpected interrupts\&. This function is triggered when an unexpected interrupt occurs\&. It provides a mechanism to handle the interrupt and display an appropriate message\&.

.PP
Handles unexpected interrupts\&.

.PP
This is a weak symbol that can be overridden by a user-defined handler\&. 
.PP
Definition at line \fB31\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SS "void HardFault_Handler (void )"

.PP
Handles hard faults\&. This function is triggered when a hard fault occurs\&. It provides a mechanism to handle the fault and display an appropriate message\&.

.PP
Handles hard faults\&.

.PP
This is a weak symbol that can be overridden by a user-defined handler\&. 
.PP
Definition at line \fB25\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
