.TH "util/error_handling.c" 3 "Fri Mar 21 2025 13:00:27" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/error_handling.c
.SH SYNOPSIS
.br
.PP
\fR#include 'util/error_handling\&.h'\fP
.br
\fR#include 'presentation/ui\&.h'\fP
.br
\fR#include 'hal/system\&.h'\fP
.br
\fR#include 'hal/uart\&.h'\fP
.br
\fR#include 'presentation/print\&.h'\fP
.br
\fR#include 'presentation/style\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBhandleError\fP (const char *hint)"
.br
.ti -1c
.RI "void \fBHardFault_Handler\fP ()"
.br
.ti -1c
.RI "void \fBDefault_Handler\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Default_Handler ()"

.PP
Definition at line \fB17\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SS "static void handleError (const char * hint)\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBBOLD\fP, \fBDIM\fP, \fBFG_RED\fP, \fBprint()\fP, \fBprint_clearConsole()\fP, \fBprintln()\fP, \fBRESET\fP, \fBsystem_softReset()\fP, \fBuart_readByte()\fP, and \fBui_printHeading()\fP\&.
.SS "void HardFault_Handler ()"

.PP
Definition at line \fB11\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
