.TH "util/error_handling.h" 3 "Wed Mar 12 2025 11:27:55" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/error_handling.h \- Contains functions to react on inevitable errors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhandleHardFault\fP ()"
.br
.ti -1c
.RI "void \fBhandleUnexpectedInterrupt\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains functions to react on inevitable errors\&. 


.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBerror_handling\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void handleHardFault ()"

.PP
Definition at line \fB11\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SS "void handleUnexpectedInterrupt ()"

.PP
Definition at line \fB17\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
