.TH "util/error_handling.h" 3 "Mon Mar 3 2025 08:08:04" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/error_handling.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhandleHardFault\fP ()"
.br
.ti -1c
.RI "void \fBhandleUnexpectedInterrupt\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void handleHardFault ()"

.PP
Definition at line \fB12\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SS "void handleUnexpectedInterrupt ()"

.PP
Definition at line \fB18\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
