.TH "GameTimer" 3 "Sun Mar 2 2025 23:39:37" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameTimer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <time\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBis_running\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBticks_total\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBticks_turn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBtime\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBbool\fP GameTimer::is_running"

.PP
Definition at line \fB25\fP of file \fBtime\&.h\fP\&.
.SS "volatile uint32_t GameTimer::ticks_total"

.PP
Definition at line \fB26\fP of file \fBtime\&.h\fP\&.
.SS "volatile uint32_t GameTimer::ticks_turn"

.PP
Definition at line \fB27\fP of file \fBtime\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
