.TH "GameState" 3 "Fri Mar 21 2025 12:20:38" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameState \- The current game state\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPlayer\fP \fBwinner\fP"
.br
.RI "None if tie or game not over\&. "
.ti -1c
.RI "\fBMode\fP \fBmode\fP"
.br
.ti -1c
.RI "volatile uint8_t \fBround\fP"
.br
.ti -1c
.RI "volatile uint8_t \fBfields_marked\fP"
.br
.ti -1c
.RI "\fBPlayer\fP \fBcurrent_player\fP"
.br
.ti -1c
.RI "uint32_t \fBtotal_ticks\fP"
.br
.ti -1c
.RI "uint32_t \fBaverage_ticks\fP"
.br
.ti -1c
.RI "uint32_t \fBcross_total_ticks\fP"
.br
.ti -1c
.RI "uint32_t \fBcross_average_ticks\fP"
.br
.ti -1c
.RI "uint32_t \fBcircle_total_ticks\fP"
.br
.ti -1c
.RI "uint32_t \fBcircle_average_ticks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The current game state\&. 

Contains important game information and several metrics 
.PP
Definition at line \fB60\fP of file \fBgame\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t GameState::average_ticks"

.PP
Definition at line \fB70\fP of file \fBgame\&.h\fP\&.
.SS "uint32_t GameState::circle_average_ticks"

.PP
Definition at line \fB76\fP of file \fBgame\&.h\fP\&.
.SS "uint32_t GameState::circle_total_ticks"

.PP
Definition at line \fB75\fP of file \fBgame\&.h\fP\&.
.SS "uint32_t GameState::cross_average_ticks"

.PP
Definition at line \fB73\fP of file \fBgame\&.h\fP\&.
.SS "uint32_t GameState::cross_total_ticks"

.PP
Definition at line \fB72\fP of file \fBgame\&.h\fP\&.
.SS "\fBPlayer\fP GameState::current_player"

.PP
Definition at line \fB66\fP of file \fBgame\&.h\fP\&.
.SS "volatile uint8_t GameState::fields_marked"

.PP
Definition at line \fB65\fP of file \fBgame\&.h\fP\&.
.SS "\fBMode\fP GameState::mode"

.PP
Definition at line \fB63\fP of file \fBgame\&.h\fP\&.
.SS "volatile uint8_t GameState::round"

.PP
Definition at line \fB64\fP of file \fBgame\&.h\fP\&.
.SS "uint32_t GameState::total_ticks"

.PP
Definition at line \fB69\fP of file \fBgame\&.h\fP\&.
.SS "\fBPlayer\fP GameState::winner"

.PP
None if tie or game not over\&. 
.PP
Definition at line \fB62\fP of file \fBgame\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
