.TH "GameTimer" 3 "Fri Mar 21 2025 12:53:28" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameTimer \- Time information of the current game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <time\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBis_running\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBticks_total\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBticks_turn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Time information of the current game\&. 
.PP
Definition at line \fB20\fP of file \fBtime\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBbool\fP GameTimer::is_running"

.PP
Definition at line \fB22\fP of file \fBtime\&.h\fP\&.
.SS "volatile uint32_t GameTimer::ticks_total"

.PP
Definition at line \fB23\fP of file \fBtime\&.h\fP\&.
.SS "volatile uint32_t GameTimer::ticks_turn"

.PP
Definition at line \fB24\fP of file \fBtime\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
