.TH "logic/input.h" 3 "Tue Mar 4 2025 13:27:31" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/input.h
.SH SYNOPSIS
.br
.PP
\fR#include 'def\&.h'\fP
.br
\fR#include 'logic/game\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBinput_handleByte\fP (uint8_t *byte, \fBGameState\fP *\fBgame_state\fP, \fBCellState\fP *\fBcell_state\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4

.RE
.PP
\fBDate\fP
.RS 4
.RE
.PP
\fBSee also\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBinput\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBbool\fP input_handleByte (uint8_t * byte, \fBGameState\fP * game_state, \fBCellState\fP * cell_state)"

.PP
Definition at line \fB38\fP of file \fBinput\&.c\fP\&.
.PP
References \fBcell_decreaseSize()\fP, \fBcell_increaseSize()\fP, \fBcell_state\fP, \fBg_timer\fP, \fBgame_state\fP, \fBhandleEscapeSequence()\fP, \fBhandlePauseResume()\fP, \fBhandleSetMark()\fP, \fBGameTimer::is_running\fP, and \fBopenControls()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
