.TH "main.c" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- Entry point for the TikTakToe game\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'def\&.h'\fP
.br
\fR#include 'hal/nvic\&.h'\fP
.br
\fR#include 'hal/uart\&.h'\fP
.br
\fR#include 'presentation/print\&.h'\fP
.br
\fR#include 'presentation/style\&.h'\fP
.br
\fR#include 'presentation/ui\&.h'\fP
.br
\fR#include 'util/input_buf\&.h'\fP
.br
\fR#include 'hal/system\&.h'\fP
.br
\fR#include 'presentation/menu\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Main function for the Tic-Tac-Toe application\&. "
.in -1c
.SH "Detailed Description"
.PP 
Entry point for the TikTakToe game\&. 

This file contains the main function, which initializes the system, handles the main menu, and manages the game flow based on user input\&.

.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Main function for the Tic-Tac-Toe application\&. Initializes the UART and input buffer, displays the main menu, and handles user input to either reset the game or exit\&. If the game is reset, the system performs a soft reset\&. If the user exits, the system enters off mode\&.

.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBmain\&.c\fP\&.
.PP
References \fB__WFI\fP, \fBDEFAULT_BOLD\fP, \fBg_input_buf\fP, \fBinput_getNext()\fP, \fBinput_init()\fP, \fBITALIC_DIM\fP, \fBmenu_showMainMenu()\fP, \fBprint()\fP, \fBprint_clearConsole()\fP, \fBprintln_styled()\fP, \fBSHOW_CURSOR\fP, \fBsystem_offMode()\fP, \fBsystem_softReset()\fP, \fBuart_init()\fP, and \fBui_printHeading()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
