.TH "md__2github_2workspace_2Architecture" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2github_2workspace_2Architecture \- 🏗️ Architecture 
.PP


.PP

.PP
This project is an embedded application, designed to run on an \fRnRF51\fP microcontroller with an \fRarm-cortex-m0\fP CPU\&. The architecture is seperated into three main layers; the hardware abstraction layer, the logic layer and the presentation layer\&. Additionally modules for the entry process and utility functions exist\&. This encapsulation allows for a flexible design\&.
.SH "🚪 Entry Module"
.PP
\fIfiles: \fBentry/entry\&.S\fP, entry/linker_script\&.ls\fP

.PP
This module is responsible for the startup process of the microcontroller\&. Here important elements, such as the entry point, interrupt vector table and memory regions are defined and actions such as copying data from ROM to RAM are performed\&.
.SH "📟 Hardware Abstraction Layer"
.PP
\fIfiles: include/hal/*\&.h, src/hal/*\&.c\fP

.PP
The hardware abstraction layer, short hal, abstracts low level operations such as register access and encapsulates these operations, allowing the layers above to refrain from interacting with any of the peripherals directly\&.
.SH "🧩 Logic Layer"
.PP
\fIfiles: include/logic/*\&.h, src/logic/*\&.c\fP

.PP
Within this layer, the game logic itself resides\&. Here you can find the main game loop, the timer and the game state\&.
.SH "🖥️ Presentation Layer"
.PP
\fIfiles: include/presentation/*\&.h, src/presentation/*\&.c\fP

.PP
This layer contains everything used to display a pretty output to the user\&. Menus, ui and styling can all be found here\&.

.PP
The seperation from the logic layer allows for flexible configuration, such as changing field sizes during the game\&.
.SH "🛠️ Utility Layer"
.PP
\fIfiles: include/util/*\&.h, src/util/*\&.c\fP

.PP
Modules used throughout the layer, or which can't be directly assigned to one certain layer can be found here\&.
.SH "➕ Other relevant files"
.PP
.IP "\(bu" 2
config\&.h\&.in / \fBconfig\&.h\fP
.IP "  \(bu" 4
The \fRconfig\&.h\&.in\fP file is used for the compile time configurations and is processed into \fR\fBconfig\&.h\fP\fP by CMake
.PP

.IP "\(bu" 2
\fBentry-S\&.c\fP
.IP "  \(bu" 4
Since Doxygen can't parse assembly files, the \fR\fBentry\&.S\fP\fP file is converted to stubbed C file by a helper script, which can then be parsed\&.
.PP

.IP "\(bu" 2
\fBmain\&.c\fP
.IP "  \(bu" 4
The main file for the game itself, containing the \fR\fBmain()\fP\fP function which is invoked by the \fRReset_Handler\fP 
.PP

.PP

