.TH "hal/memset.c" 3 "Mon Mar 3 2025 16:55:31" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal/memset.c
.SH SYNOPSIS
.br
.PP
\fR#include 'hal/memset\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBmemset\fP (void *ptr, const int x, size_t n)"
.br
.RI "Sets the first n bytes of the block of memory pointed by ptr to the specified value\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * memset (void * ptr, int x, size_t n)"

.PP
Sets the first n bytes of the block of memory pointed by ptr to the specified value\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP Pointer to the block of memory to fill 
.br
\fIx\fP Value to be set\&. The value is passed as an int, but the function fills the block of memory using the unsigned char conversion of this value 
.br
\fIn\fP Number of bytes to be set to the value
.RE
.PP
\fBReturns\fP
.RS 4
A pointer to the memory area ptr 
.RE
.PP

.PP
Definition at line \fB5\fP of file \fBmemset\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
