.TH "hal/memset.h" 3 "Fri Mar 21 2025 12:43:06" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal/memset.h \- Contains a simple implementation of memset\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBmemset\fP (void *ptr, int x, size_t n)"
.br
.RI "Simple implementation of memset\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains a simple implementation of memset\&. 


.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBmemset\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void * memset (void * ptr, int x, size_t n)"

.PP
Simple implementation of memset\&. Sets the first \fBn\fP bytes of the block of memory pointed to by \fBptr\fP to the specified value \fBx\fP

.PP
\fBParameters\fP
.RS 4
\fIptr\fP Pointer to the block of memory to fill 
.br
\fIx\fP Value to be set\&. The value is passed as an int, but the function fills the block of memory using the unsigned char conversion of this value 
.br
\fIn\fP Number of bytes to be set to the value
.RE
.PP
\fBReturns\fP
.RS 4
A pointer to the memory area 
.RE
.PP

.PP
Definition at line \fB5\fP of file \fBmemset\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
