.TH "presentation/menu.h" 3 "Fri Mar 21 2025 13:00:26" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/menu.h \- Contains functions for presentation of the menu\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'logic/game\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRETURN_MENU_HINT\fP   '\\nPress any key to return to the menu\&.\&.\&.'"
.br
.ti -1c
.RI "#define \fBARROW_LEFT\fP   '<LEFT>'"
.br
.ti -1c
.RI "#define \fBARROW_UP\fP   '<UP>'"
.br
.ti -1c
.RI "#define \fBARROW_RIGHT\fP   '<RIGHT>'"
.br
.ti -1c
.RI "#define \fBARROW_DOWN\fP   '<DOWN>'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBmenu_showMainMenu\fP ()"
.br
.ti -1c
.RI "void \fBmenu_showControls\fP (const char *continue_hint)"
.br
.ti -1c
.RI "void \fBmenu_showCredits\fP ()"
.br
.ti -1c
.RI "void \fBmenu_showGameOver\fP (const \fBGameState\fP *game_info)"
.br
.ti -1c
.RI "void \fBmenu_anyKeyToContinue\fP (const char *continue_hint)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains functions for presentation of the menu\&. 


.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBmenu\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARROW_DOWN   '<DOWN>'"

.PP
Definition at line \fB27\fP of file \fBmenu\&.h\fP\&.
.SS "#define ARROW_LEFT   '<LEFT>'"

.PP
Definition at line \fB24\fP of file \fBmenu\&.h\fP\&.
.SS "#define ARROW_RIGHT   '<RIGHT>'"

.PP
Definition at line \fB26\fP of file \fBmenu\&.h\fP\&.
.SS "#define ARROW_UP   '<UP>'"

.PP
Definition at line \fB25\fP of file \fBmenu\&.h\fP\&.
.SS "#define RETURN_MENU_HINT   '\\nPress any key to return to the menu\&.\&.\&.'"

.PP
Definition at line \fB16\fP of file \fBmenu\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void menu_anyKeyToContinue (const char * continue_hint)"

.PP
Definition at line \fB192\fP of file \fBmenu\&.c\fP\&.
.PP
References \fB__WFI\fP, \fBg_input_buf\fP, \fBinput_getNext()\fP, \fBITALIC_DIM\fP, and \fBprintln_styled()\fP\&.
.SS "void menu_showControls (const char * continue_hint)"

.PP
Definition at line \fB144\fP of file \fBmenu\&.c\fP\&.
.PP
References \fBARROW_DOWN\fP, \fBARROW_LEFT\fP, \fBARROW_RIGHT\fP, \fBARROW_UP\fP, \fBBOLD_CROSS\fP, \fBDEFAULT_BOLD\fP, \fBITALIC_DIM\fP, \fBmenu_anyKeyToContinue()\fP, \fBprint()\fP, \fBprint_clearConsole()\fP, \fBprint_styled()\fP, \fBprintln()\fP, \fBprintln_styled()\fP, and \fBui_printHeading()\fP\&.
.SS "void menu_showCredits ()"

.PP
Definition at line \fB135\fP of file \fBmenu\&.c\fP\&.
.PP
References \fBmenu_anyKeyToContinue()\fP, \fBprint_clearConsole()\fP, \fBprintln()\fP, \fBRETURN_MENU_HINT\fP, and \fBui_printHeading()\fP\&.
.SS "void menu_showGameOver (const \fBGameState\fP * game_info)"

.PP
Definition at line \fB78\fP of file \fBmenu\&.c\fP\&.
.PP
References \fBGameState::average_ticks\fP, \fBBOLD_CIRCLE\fP, \fBBOLD_CROSS\fP, \fBCELLS_PER_COL\fP, \fBGameState::circle_average_ticks\fP, \fBGameState::circle_total_ticks\fP, \fBGameState::cross_average_ticks\fP, \fBGameState::cross_total_ticks\fP, \fBcursor_moveTo()\fP, \fBDEFAULT_BOLD\fP, \fBDEFAULT_ITALIC\fP, \fBERASE_LINE_FROM_CURSOR\fP, \fBGameState::fields_marked\fP, \fBg_cell_size\fP, \fBHEADING_LINES\fP, \fBCellSize::height\fP, \fBmenu_anyKeyToContinue()\fP, \fBprint()\fP, \fBprint_clearConsole()\fP, \fBprint_styled()\fP, \fBprintln_int()\fP, \fBprintln_styled()\fP, \fBprintWinnerBanner()\fP, \fBRESET\fP, \fBRETURN_MENU_HINT\fP, \fBGameState::round\fP, \fBGameState::total_ticks\fP, \fBui_gameOver()\fP, and \fBui_printHeading()\fP\&.
.SS "\fBbool\fP menu_showMainMenu ()"

.PP
Definition at line \fB34\fP of file \fBmenu\&.c\fP\&.
.PP
References \fB__WFI\fP, \fBg_input_buf\fP, \fBgame_run()\fP, \fBHIDE_CURSOR\fP, \fBinput_getNext()\fP, \fBmenu_showControls()\fP, \fBmenu_showCredits()\fP, \fBprint()\fP, \fBprintMainMenu()\fP, \fBPVE\fP, \fBPVP\fP, and \fBRETURN_MENU_HINT\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
