.TH "hal/random.h" 3 "Sat Mar 22 2025 15:19:13" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal/random.h \- Header file for the RNG HAL\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRNG_BASE_ADDRESS\fP   0x4000D000"
.br
.RI "Base address of the RNG peripheral\&. "
.ti -1c
.RI "#define \fBRNG_START\fP   0x000"
.br
.RI "Task starting the random number generator\&. "
.ti -1c
.RI "#define \fBRNG_STOP\fP   0x004"
.br
.RI "Task stopping the random number generator\&. "
.ti -1c
.RI "#define \fBRNG_VALRDY\fP   0x100"
.br
.RI "Event generated when new number is read\&. "
.ti -1c
.RI "#define \fBRNG_SHORTS\fP   0x200"
.br
.RI "Shortcut register\&. "
.ti -1c
.RI "#define \fBRNG_INTEN\fP   0x300"
.br
.RI "Enable or disable interrupt\&. "
.ti -1c
.RI "#define \fBRNG_INTENSET\fP   0x304"
.br
.RI "Enable interrupt\&. "
.ti -1c
.RI "#define \fBRNG_INTENCLR\fP   0x308"
.br
.RI "Disable interrupt\&. "
.ti -1c
.RI "#define \fBRNG_CONFIG\fP   0x504"
.br
.RI "Configuration register\&. "
.ti -1c
.RI "#define \fBRNG_VALUE\fP   0x508"
.br
.RI "Output random number\&. "
.ti -1c
.RI "#define \fBRNG_TASK_START\fP   1"
.br
.RI "Value for starting a Task\&. "
.ti -1c
.RI "#define \fBRNG_EVENT_TRIGGER\fP   1"
.br
.RI "Value for setting/starting an Event\&. "
.ti -1c
.RI "#define \fBRNG_EVENT_CLEAR\fP   0"
.br
.RI "Value for clearing/stopping an Event\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrng_init\fP ()"
.br
.RI "Enables the generation of random numbers\&. "
.ti -1c
.RI "uint8_t \fBrng_getRandomValue_immediately\fP ()"
.br
.RI "Get the Random Value from the generator immediately\&. "
.ti -1c
.RI "uint8_t \fBrng_getRandomValue_waiting\fP ()"
.br
.RI "Get the Random Value from the generator by polling and waiting\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the RNG HAL\&. 

This file contains the declarations and macros for interacting with the RNG peripheral, including initialization and random number retrieval\&.

.PP
\fBSee also\fP
.RS 4
\fBrandom\&.c\fP
.RE
.PP
\fBNote\fP
.RS 4
Based on version by Thomas Vogt
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBrandom\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define RNG_BASE_ADDRESS   0x4000D000"

.PP
Base address of the RNG peripheral\&. 
.PP
Definition at line \fB28\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_CONFIG   0x504"

.PP
Configuration register\&. 
.PP
Definition at line \fB43\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_EVENT_CLEAR   0"

.PP
Value for clearing/stopping an Event\&. 
.PP
Definition at line \fB49\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_EVENT_TRIGGER   1"

.PP
Value for setting/starting an Event\&. 
.PP
Definition at line \fB48\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_INTEN   0x300"

.PP
Enable or disable interrupt\&. 
.PP
Definition at line \fB40\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_INTENCLR   0x308"

.PP
Disable interrupt\&. 
.PP
Definition at line \fB42\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_INTENSET   0x304"

.PP
Enable interrupt\&. 
.PP
Definition at line \fB41\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_SHORTS   0x200"

.PP
Shortcut register\&. 
.PP
Definition at line \fB39\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_START   0x000"

.PP
Task starting the random number generator\&. 
.PP
Definition at line \fB32\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_STOP   0x004"

.PP
Task stopping the random number generator\&. 
.PP
Definition at line \fB33\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_TASK_START   1"

.PP
Value for starting a Task\&. 
.PP
Definition at line \fB47\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_VALRDY   0x100"

.PP
Event generated when new number is read\&. 
.PP
Definition at line \fB36\fP of file \fBrandom\&.h\fP\&.
.SS "#define RNG_VALUE   0x508"

.PP
Output random number\&. 
.PP
Definition at line \fB44\fP of file \fBrandom\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "uint8_t rng_getRandomValue_immediately ()"

.PP
Get the Random Value from the generator immediately\&. The function does not wait for the next value to be generated\&. It reads the current value from the RNG peripheral\&.

.PP
\fBReturns\fP
.RS 4
uint8_t A random byte\&. 
.RE
.PP

.PP
Definition at line \fB27\fP of file \fBrandom\&.c\fP\&.
.PP
References \fBregister_read()\fP, \fBRNG_BASE_ADDRESS\fP, and \fBRNG_VALUE\fP\&.
.SS "uint8_t rng_getRandomValue_waiting ()"

.PP
Get the Random Value from the generator by polling and waiting\&. This function blocks until the RNG peripheral indicates that a new random value is ready\&. It then retrieves and returns the random byte\&.

.PP
\fBReturns\fP
.RS 4
uint8_t A random byte\&. 
.RE
.PP

.PP
Definition at line \fB36\fP of file \fBrandom\&.c\fP\&.
.PP
References \fBregister_read()\fP, \fBregister_write()\fP, \fBRNG_BASE_ADDRESS\fP, \fBRNG_EVENT_CLEAR\fP, \fBrng_getRandomValue_immediately()\fP, and \fBRNG_VALRDY\fP\&.
.SS "void rng_init ()"

.PP
Enables the generation of random numbers\&. 
.PP
Definition at line \fB21\fP of file \fBrandom\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBRNG_BASE_ADDRESS\fP, \fBRNG_START\fP, and \fBRNG_TASK_START\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
