.TH "hal/register_access.c" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal/register_access.c \- Register Access Implementation\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'hal/register_access\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBregister_write\fP (const uint32_t address, const uint32_t value)"
.br
.RI "Write a value to a hardware register\&. "
.ti -1c
.RI "uint32_t \fBregister_read\fP (const uint32_t address)"
.br
.RI "Read a value from a hardware register\&. "
.in -1c
.SH "Detailed Description"
.PP 
Register Access Implementation\&. 


.PP
\fBSee also\fP
.RS 4
\fBregister_access\&.h\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Thomas Vogt 

.PP
Sven Reis
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBregister_access\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "uint32_t register_read (uint32_t address)"

.PP
Read a value from a hardware register\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddress\fP Memory address of the register\&.
.RE
.PP
\fBReturns\fP
.RS 4
Value read from the register\&. 
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBregister_access\&.c\fP\&.
.SS "void register_write (uint32_t address, uint32_t value)"

.PP
Write a value to a hardware register\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddress\fP Memory address of the register\&. 
.br
\fIvalue\fP Value to write to the register\&. 
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBregister_access\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
