.TH "presentation/style.c" 3 "Fri Mar 21 2025 12:53:28" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/style.c
.SH SYNOPSIS
.br
.PP
\fR#include 'presentation/style\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_BOLD\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_ITALIC\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_DIM\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBBOLD_DIM\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBITALIC_DIM\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_CIRCLE\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBBOLD_CIRCLE\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_CROSS\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBBOLD_CROSS\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBHEADING_STYLE\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBStyle\fP BOLD_CIRCLE"
\fBInitial value:\fP
.nf
= {
    \&.fg_color = FG_MAGENTA,
    \&.font_style = BOLD,
}
.PP
.fi

.PP
Definition at line \fB29\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP BOLD_CROSS"
\fBInitial value:\fP
.nf
= {
    \&.fg_color = FG_GREEN,
    \&.font_style = BOLD,
}
.PP
.fi

.PP
Definition at line \fB38\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP BOLD_DIM"
\fBInitial value:\fP
.nf
= {
    \&.font_style = BOLD,
    \&.fg_color = DIM,
}
.PP
.fi

.PP
Definition at line \fB15\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_BOLD"
\fBInitial value:\fP
.nf
= {
    \&.font_style = BOLD,
}
.PP
.fi

.PP
Definition at line \fB3\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_CIRCLE"
\fBInitial value:\fP
.nf
= {
    \&.fg_color = FG_MAGENTA,
}
.PP
.fi

.PP
Definition at line \fB25\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_CROSS"
\fBInitial value:\fP
.nf
= {
    \&.fg_color = FG_GREEN,
}
.PP
.fi

.PP
Definition at line \fB34\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_DIM"
\fBInitial value:\fP
.nf
= {
    \&.font_style = DIM,
}
.PP
.fi

.PP
Definition at line \fB11\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_ITALIC"
\fBInitial value:\fP
.nf
= {
    \&.font_style = ITALIC,
}
.PP
.fi

.PP
Definition at line \fB7\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP HEADING_STYLE"
\fBInitial value:\fP
.nf
= {
    \&.fg_color = FG_BLUE,
    \&.font_style = BOLD,
}
.PP
.fi

.PP
Definition at line \fB43\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP ITALIC_DIM"
\fBInitial value:\fP
.nf
= {
    \&.font_style = ITALIC,
    \&.fg_color = DIM,
}
.PP
.fi

.PP
Definition at line \fB20\fP of file \fBstyle\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
