.TH "presentation/style.h" 3 "Fri Mar 21 2025 12:20:37" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/style.h \- Contains several constants to simplify the styling of output\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBStyle\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLEAR_SCREEN\fP   '\\e[1;1H\\e[2J'"
.br
.ti -1c
.RI "#define \fBDEFAULT\fP   ''"
.br
.ti -1c
.RI "#define \fBRESET\fP   '\\e[0m'"
.br
.ti -1c
.RI "#define \fBFG_RED\fP   '\\e[31m'"
.br
.ti -1c
.RI "#define \fBFG_GREEN\fP   '\\e[32m'"
.br
.ti -1c
.RI "#define \fBFG_YELLOW\fP   '\\e[33m'"
.br
.ti -1c
.RI "#define \fBFG_BLUE\fP   '\\e[34m'"
.br
.ti -1c
.RI "#define \fBFG_MAGENTA\fP   '\\e[35m'"
.br
.ti -1c
.RI "#define \fBBG_GREEN\fP   '\\e[42m'"
.br
.ti -1c
.RI "#define \fBBG_YELLOW\fP   '\\e[43m'"
.br
.ti -1c
.RI "#define \fBBOLD\fP   '\\e[1m'"
.br
.ti -1c
.RI "#define \fBDIM\fP   '\\e[2m'"
.br
.ti -1c
.RI "#define \fBITALIC\fP   '\\e[3m'"
.br
.ti -1c
.RI "#define \fBINVERSE\fP   '\\e[7m'"
.br
.ti -1c
.RI "#define \fBHIDDEN\fP   '\\e[8m'"
.br
.ti -1c
.RI "#define \fBHIDE_CURSOR\fP   '\\e[?25l'"
.br
.ti -1c
.RI "#define \fBSHOW_CURSOR\fP   '\\e[?25h'"
.br
.ti -1c
.RI "#define \fBERASE_LINE_FROM_CURSOR\fP   '\\e[0K'"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_BOLD\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_ITALIC\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_DIM\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBBOLD_DIM\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBITALIC_DIM\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_CIRCLE\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBBOLD_CIRCLE\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBDEFAULT_CROSS\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBBOLD_CROSS\fP"
.br
.ti -1c
.RI "const \fBStyle\fP \fBHEADING_STYLE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains several constants to simplify the styling of output\&. 


.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBstyle\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BG_GREEN   '\\e[42m'"

.PP
Definition at line \fB31\fP of file \fBstyle\&.h\fP\&.
.SS "#define BG_YELLOW   '\\e[43m'"

.PP
Definition at line \fB32\fP of file \fBstyle\&.h\fP\&.
.SS "#define BOLD   '\\e[1m'"

.PP
Definition at line \fB34\fP of file \fBstyle\&.h\fP\&.
.SS "#define CLEAR_SCREEN   '\\e[1;1H\\e[2J'"

.PP
Definition at line \fB21\fP of file \fBstyle\&.h\fP\&.
.SS "#define DEFAULT   ''"

.PP
Definition at line \fB22\fP of file \fBstyle\&.h\fP\&.
.SS "#define DIM   '\\e[2m'"

.PP
Definition at line \fB35\fP of file \fBstyle\&.h\fP\&.
.SS "#define ERASE_LINE_FROM_CURSOR   '\\e[0K'"

.PP
Definition at line \fB43\fP of file \fBstyle\&.h\fP\&.
.SS "#define FG_BLUE   '\\e[34m'"

.PP
Definition at line \fB28\fP of file \fBstyle\&.h\fP\&.
.SS "#define FG_GREEN   '\\e[32m'"

.PP
Definition at line \fB26\fP of file \fBstyle\&.h\fP\&.
.SS "#define FG_MAGENTA   '\\e[35m'"

.PP
Definition at line \fB29\fP of file \fBstyle\&.h\fP\&.
.SS "#define FG_RED   '\\e[31m'"

.PP
Definition at line \fB25\fP of file \fBstyle\&.h\fP\&.
.SS "#define FG_YELLOW   '\\e[33m'"

.PP
Definition at line \fB27\fP of file \fBstyle\&.h\fP\&.
.SS "#define HIDDEN   '\\e[8m'"

.PP
Definition at line \fB38\fP of file \fBstyle\&.h\fP\&.
.SS "#define HIDE_CURSOR   '\\e[?25l'"

.PP
Definition at line \fB40\fP of file \fBstyle\&.h\fP\&.
.SS "#define INVERSE   '\\e[7m'"

.PP
Definition at line \fB37\fP of file \fBstyle\&.h\fP\&.
.SS "#define ITALIC   '\\e[3m'"

.PP
Definition at line \fB36\fP of file \fBstyle\&.h\fP\&.
.SS "#define RESET   '\\e[0m'"

.PP
Definition at line \fB23\fP of file \fBstyle\&.h\fP\&.
.SS "#define SHOW_CURSOR   '\\e[?25h'"

.PP
Definition at line \fB41\fP of file \fBstyle\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBStyle\fP BOLD_CIRCLE\fR [extern]\fP"

.PP
Definition at line \fB29\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP BOLD_CROSS\fR [extern]\fP"

.PP
Definition at line \fB38\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP BOLD_DIM\fR [extern]\fP"

.PP
Definition at line \fB15\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_BOLD\fR [extern]\fP"

.PP
Definition at line \fB3\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_CIRCLE\fR [extern]\fP"

.PP
Definition at line \fB25\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_CROSS\fR [extern]\fP"

.PP
Definition at line \fB34\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_DIM\fR [extern]\fP"

.PP
Definition at line \fB11\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP DEFAULT_ITALIC\fR [extern]\fP"

.PP
Definition at line \fB7\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP HEADING_STYLE\fR [extern]\fP"

.PP
Definition at line \fB43\fP of file \fBstyle\&.c\fP\&.
.SS "const \fBStyle\fP ITALIC_DIM\fR [extern]\fP"

.PP
Definition at line \fB20\fP of file \fBstyle\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
