.TH "Style" 3 "Fri Mar 21 2025 12:45:17" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Style
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <style\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfg_color\fP"
.br
.ti -1c
.RI "char * \fBbg_color\fP"
.br
.ti -1c
.RI "char * \fBfont_style\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBstyle\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* Style::bg_color"

.PP
Definition at line \fB17\fP of file \fBstyle\&.h\fP\&.
.SS "char* Style::fg_color"

.PP
Definition at line \fB16\fP of file \fBstyle\&.h\fP\&.
.SS "char* Style::font_style"

.PP
Definition at line \fB18\fP of file \fBstyle\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
