.TH "hal/system.c" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal/system.c \- Implementation of system control functions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'hal/system\&.h'\fP
.br
\fR#include 'def\&.h'\fP
.br
\fR#include 'hal/register_access\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsystem_softReset\fP ()"
.br
.RI "Trigger a soft reset of the system\&. "
.ti -1c
.RI "void \fBsystem_offMode\fP ()"
.br
.RI "Triggers 'off' mode of the system\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of system control functions\&. 


.PP
\fBSee also\fP
.RS 4
\fBsystem\&.h\fP
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBsystem\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void system_offMode ()"

.PP
Triggers 'off' mode of the system\&. 
.PP
\fBNote\fP
.RS 4
\fBNever returns\fP 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBsystem\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBSYS_POWER\fP, and \fBSYS_SYSTEMOFF\fP\&.
.SS "void system_softReset ()"

.PP
Trigger a soft reset of the system\&. 
.PP
\fBNote\fP
.RS 4
\fBNever returns\fP 
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBsystem\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBSYS_AIRCR\fP, \fBSYS_SYSRESETREQ\fP, and \fBSYS_VECTKEY\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
