.TH "hal_low/system.h" 3 "Sun Mar 2 2025 23:35:50" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal_low/system.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYS_AIRCR\fP   0xE000ED0C"
.br
.ti -1c
.RI "#define \fBSYS_VECTKEY\fP   (0x5FA << 16)"
.br
.ti -1c
.RI "#define \fBSYS_SYSRESETREQ\fP   (1 << 2)"
.br
.ti -1c
.RI "#define \fBSYS_POWER\fP   0x40000000"
.br
.ti -1c
.RI "#define \fBSYS_SYSTEMOFF\fP   0x500"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsystem_softReset\fP ()"
.br
.ti -1c
.RI "void \fBsystem_offMode\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SYS_AIRCR   0xE000ED0C"

.PP
Definition at line \fB4\fP of file \fBsystem\&.h\fP\&.
.SS "#define SYS_POWER   0x40000000"

.PP
Definition at line \fB8\fP of file \fBsystem\&.h\fP\&.
.SS "#define SYS_SYSRESETREQ   (1 << 2)"

.PP
Definition at line \fB6\fP of file \fBsystem\&.h\fP\&.
.SS "#define SYS_SYSTEMOFF   0x500"

.PP
Definition at line \fB9\fP of file \fBsystem\&.h\fP\&.
.SS "#define SYS_VECTKEY   (0x5FA << 16)"

.PP
Definition at line \fB5\fP of file \fBsystem\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void system_offMode ()"

.PP
Definition at line \fB15\fP of file \fBsystem\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBSYS_POWER\fP, and \fBSYS_SYSTEMOFF\fP\&.
.SS "void system_softReset ()"

.PP
Definition at line \fB6\fP of file \fBsystem\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBSYS_AIRCR\fP, \fBSYS_SYSRESETREQ\fP, and \fBSYS_VECTKEY\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
