.TH "hal/system.c" 3 "Fri Mar 21 2025 13:57:37" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal/system.c
.SH SYNOPSIS
.br
.PP
\fR#include 'hal/system\&.h'\fP
.br
\fR#include 'def\&.h'\fP
.br
\fR#include 'hal/register_access\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsystem_softReset\fP ()"
.br
.RI "Trigger a soft reset of the system\&. "
.ti -1c
.RI "void \fBsystem_offMode\fP ()"
.br
.RI "Triggers 'off' mode of the system\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void system_offMode ()"

.PP
Triggers 'off' mode of the system\&. 
.PP
\fBNote\fP
.RS 4
\fBNever returns\fP 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBsystem\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBSYS_POWER\fP, and \fBSYS_SYSTEMOFF\fP\&.
.SS "void system_softReset ()"

.PP
Trigger a soft reset of the system\&. 
.PP
\fBNote\fP
.RS 4
\fBNever returns\fP 
.RE
.PP

.PP
Definition at line \fB6\fP of file \fBsystem\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBSYS_AIRCR\fP, \fBSYS_SYSRESETREQ\fP, and \fBSYS_VECTKEY\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
