.TH "hal/uart.c" 3 "Fri Mar 21 2025 12:53:28" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal/uart.c
.SH SYNOPSIS
.br
.PP
\fR#include 'hal/uart\&.h'\fP
.br
\fR#include 'hal/nvic\&.h'\fP
.br
\fR#include 'hal/register_access\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBuart_init\fP (const \fBbool\fP with_interrupts)"
.br
.RI "Initializing the UART with the following Settings: 115200-8-N-1\&. "
.ti -1c
.RI "void \fBuart_writeByte\fP (const uint8_t data)"
.br
.RI "Writes/Sends a byte over the serial Port\&. "
.ti -1c
.RI "uint8_t \fBuart_readByte\fP ()"
.br
.RI "Read/Receive a byte from the serial Port\&. "
.ti -1c
.RI "uint8_t \fBuart_readByteBlocking\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4

.RE
.PP
\fBDate\fP
.RS 4
.RE
.PP
\fBSee also\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBuart\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void uart_init (\fBbool\fP with_interrupts)"

.PP
Initializing the UART with the following Settings: 115200-8-N-1\&. 
.PP
\fBParameters\fP
.RS 4
\fIwith_interrupts\fP Wether or not interrupts should be triggered 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBuart\&.c\fP\&.
.PP
References \fBInterrupt_ID2\fP, \fBInterrupt_Set_Enable\fP, \fBregister_write()\fP, \fBUART_BASE_ADDRESS\fP, \fBUART_ENABLE\fP, \fBUART_INT_RXDRDY\fP, \fBUART_INTENSET\fP, \fBUART_STARTRX\fP, \fBUART_STARTTX\fP, and \fBUART_TASK_START\fP\&.
.SS "uint8_t uart_readByte ()"

.PP
Read/Receive a byte from the serial Port\&. 
.PP
\fBReturns\fP
.RS 4
uint8_t received Byte or 0 (zero) if nothing was received 
.RE
.PP

.PP
Definition at line \fB81\fP of file \fBuart\&.c\fP\&.
.PP
References \fBregister_read()\fP, \fBregister_write()\fP, \fBUART_BASE_ADDRESS\fP, \fBUART_EVENT_CLEAR\fP, \fBUART_RXD\fP, and \fBUART_RXDRDY\fP\&.
.SS "uint8_t uart_readByteBlocking ()"

.PP
Definition at line \fB100\fP of file \fBuart\&.c\fP\&.
.SS "void uart_writeByte (uint8_t data)"

.PP
Writes/Sends a byte over the serial Port\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP byte to send 
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBuart\&.c\fP\&.
.PP
References \fBregister_write()\fP, \fBUART_BASE_ADDRESS\fP, and \fBUART_TXD\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
