.TH "presentation/ui.h" 3 "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/ui.h \- Contains different functions for the presentation of the in-game user interface (everything besides the actual game field)\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'logic/game\&.h'\fP
.br
\fR#include 'presentation/ascii_art\&.h'\fP
.br
\fR#include 'presentation/cell\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTURN_ROW\fP   1 + \fBHEADING_LINES\fP"
.br
.RI "Row position for displaying the turn text\&. "
.ti -1c
.RI "#define \fBTIMER_ROW\fP"
.br
.RI "Row position for displaying the timer\&. "
.ti -1c
.RI "#define \fBFULL_PROGRESS_ELEMENT\fP   '\-'"
.br
.RI "Full progress bar element\&. "
.ti -1c
.RI "#define \fBHALF_PROGRESS_ELEMENT\fP   '_'"
.br
.RI "Half progress bar element\&. "
.ti -1c
.RI "#define \fBEMPTY_PROGRESS_ELEMENT\fP   ''"
.br
.RI "Empty progress bar element\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBui_displayTimer\fP (uint16_t remaining_time, uint16_t total_time)"
.br
.RI "Writes the timer text to the screen\&. "
.ti -1c
.RI "void \fBui_updateTimer\fP (uint16_t remaining_time, uint16_t total_time)"
.br
.RI "Updates the time on the screen\&. "
.ti -1c
.RI "void \fBui_displayTurn\fP (uint8_t current_turn, \fBPlayer\fP player)"
.br
.RI "Writes the turn text to the screen\&. "
.ti -1c
.RI "void \fBui_updateTurn\fP (uint8_t current_turn, \fBPlayer\fP player)"
.br
.RI "Updates the turn number on the screen\&. "
.ti -1c
.RI "void \fBui_printStartingPlayer\fP (\fBPlayer\fP starting_player, \fBMode\fP mode)"
.br
.RI "Displays the starting player and mode\&. "
.ti -1c
.RI "void \fBui_printHeading\fP ()"
.br
.RI "Prints the game heading to the screen\&. "
.ti -1c
.RI "void \fBui_gameOver\fP ()"
.br
.RI "Displays the 'Game Over' message on the screen\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains different functions for the presentation of the in-game user interface (everything besides the actual game field)\&. 

This file provides functions to display and update the timer, turn text, and other UI elements for the game\&. It also includes macros for rendering progress elements and constants for positioning UI elements\&.

.PP
\fBSee also\fP
.RS 4
\fBui\&.c\fP
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBui\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define EMPTY_PROGRESS_ELEMENT   ''"

.PP
Empty progress bar element\&. 
.PP
Definition at line \fB51\fP of file \fBui\&.h\fP\&.
.SS "#define FULL_PROGRESS_ELEMENT   '\-'"

.PP
Full progress bar element\&. 
.PP
Definition at line \fB49\fP of file \fBui\&.h\fP\&.
.SS "#define HALF_PROGRESS_ELEMENT   '_'"

.PP
Half progress bar element\&. 
.PP
Definition at line \fB50\fP of file \fBui\&.h\fP\&.
.SS "#define TIMER_ROW"
\fBValue:\fP
.nf
    (CELLS_PER_COL == 2 ? FIELD_HEIGHT + (FIELD_HEIGHT % 2) + 1 + HEADING_LINES \\
                        : FIELD_HEIGHT + (FIELD_HEIGHT % 2) \- 1 + HEADING_LINES)
.PP
.fi

.PP
Row position for displaying the timer\&. The timer row position is calculated based on the number of cells per column\&. If the number of cells per column is 2, the calculation has to be adjusted 
.PP
Definition at line \fB40\fP of file \fBui\&.h\fP\&.
.SS "#define TURN_ROW   1 + \fBHEADING_LINES\fP"

.PP
Row position for displaying the turn text\&. 
.PP
Definition at line \fB30\fP of file \fBui\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void ui_displayTimer (uint16_t remaining_time, uint16_t total_time)"

.PP
Writes the timer text to the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIremaining_time\fP The remaining time in seconds\&. 
.br
\fItotal_time\fP The total time in seconds\&. 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBui\&.c\fP\&.
.PP
References \fBcursor_moveTo()\fP, \fBITALIC_DIM\fP, \fBprint()\fP, \fBprint_styled()\fP, \fBTIMER_ROW\fP, and \fBui_updateTimer()\fP\&.
.SS "void ui_displayTurn (uint8_t current_turn, \fBPlayer\fP player)"

.PP
Writes the turn text to the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_turn\fP The current turn number\&. 
.br
\fIplayer\fP The player whose turn it is (Circle or Cross)\&. 
.RE
.PP

.PP
Definition at line \fB86\fP of file \fBui\&.c\fP\&.
.PP
References \fBcursor_moveTo()\fP, \fBDEFAULT_BOLD\fP, \fBDEFAULT_ITALIC\fP, \fBprint_styled()\fP, \fBTURN_ROW\fP, and \fBui_updateTurn()\fP\&.
.SS "void ui_gameOver ()"

.PP
Displays the 'Game Over' message on the screen\&. 
.PP
Definition at line \fB114\fP of file \fBui\&.c\fP\&.
.PP
References \fBcursor_moveTo()\fP, \fBDEFAULT_BOLD\fP, \fBERASE_LINE_FROM_CURSOR\fP, \fBprint()\fP, \fBprint_styled()\fP, \fBTIMER_ROW\fP, and \fBTURN_ROW\fP\&.
.SS "void ui_printHeading ()"

.PP
Prints the game heading to the screen\&. 
.PP
Definition at line \fB124\fP of file \fBui\&.c\fP\&.
.PP
References \fBcursor_moveTo()\fP, \fBHEADING\fP, \fBHEADING_STYLE\fP, and \fBprint_styled()\fP\&.
.SS "void ui_printStartingPlayer (\fBPlayer\fP starting_player, \fBMode\fP mode)"

.PP
Displays the starting player and mode\&. 
.PP
\fBParameters\fP
.RS 4
\fIstarting_player\fP The player who starts the game\&. 
.br
\fImode\fP The game mode (e\&.g\&., PVE or PVP)\&. 
.RE
.PP

.PP
Definition at line \fB130\fP of file \fBui\&.c\fP\&.
.PP
References \fBBOLD\fP, \fBCircle\fP, \fBCIRCLE_STARTS\fP, \fBCOMPUTER_STARTS\fP, \fBCross\fP, \fBCROSS_STARTS\fP, \fBDEFAULT_CIRCLE\fP, \fBDEFAULT_CROSS\fP, \fBFG_RED\fP, \fBmenu_anyKeyToContinue()\fP, \fBNone\fP, \fBPLAYER_STARTS\fP, \fBprint_clearConsole()\fP, \fBprint_styled()\fP, \fBPVE\fP, and \fBui_printHeading()\fP\&.
.SS "void ui_updateTimer (uint16_t remaining_time, uint16_t total_time)"

.PP
Updates the time on the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIremaining_time\fP The remaining time in seconds\&. 
.br
\fItotal_time\fP The total time in seconds\&. 
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBui\&.c\fP\&.
.PP
References \fBBOLD\fP, \fBcursor_moveTo()\fP, \fBDIM\fP, \fBEMPTY_PROGRESS_ELEMENT\fP, \fBERASE_LINE_FROM_CURSOR\fP, \fBFG_GREEN\fP, \fBFG_RED\fP, \fBFG_YELLOW\fP, \fBFULL_PROGRESS_ELEMENT\fP, \fBg_timer\fP, \fBHALF_PROGRESS_ELEMENT\fP, \fBGameTimer::is_running\fP, \fBITALIC_DIM\fP, \fBprint()\fP, \fBprint_styled()\fP, \fBprintln_styled()\fP, \fBTIMER_ROW\fP, and \fBuart_writeByte()\fP\&.
.SS "void ui_updateTurn (uint8_t current_turn, \fBPlayer\fP player)"

.PP
Updates the turn number on the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_turn\fP The current turn number\&. 
.br
\fIplayer\fP The player whose turn it is (Circle or Cross)\&. 
.RE
.PP

.PP
Definition at line \fB96\fP of file \fBui\&.c\fP\&.
.PP
References \fBBOLD_CIRCLE\fP, \fBBOLD_CROSS\fP, \fBCircle\fP, \fBCross\fP, \fBcursor_moveTo()\fP, \fBFG_GREEN\fP, \fBFG_MAGENTA\fP, \fBprint()\fP, \fBprint_int()\fP, \fBprint_styled()\fP, and \fBTURN_ROW\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
