.TH "logic/winning.h" 3 "Fri Mar 21 2025 12:43:06" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/winning.h \- Contains the function for checking if someone has won\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'logic/game\&.h'\fP
.br
\fR#include 'util/math\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPlayer\fP \fBwinning_checkForWinner\fP (\fBCellState\fP *\fBcell_state\fP, \fBCell\fP *winner_cells[\fBmax\fP(\fBCELLS_PER_COL\fP, \fBCELLS_PER_ROW\fP)])"
.br
.RI "Checks at the end of the round if someone has won\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the function for checking if someone has won\&. 


.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBwinning\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBPlayer\fP winning_checkForWinner (\fBCellState\fP * cell_state, \fBCell\fP * winner_cells[max(CELLS_PER_COL, CELLS_PER_ROW)])"

.PP
Checks at the end of the round if someone has won\&. 
.PP
\fBParameters\fP
.RS 4
\fIcell_state\fP Current state of the cells 
.br
\fIwinner_cells\fP If a player won, the relevant cells will be written to this buffer
.RE
.PP
\fBReturns\fP
.RS 4
The player who won 
.RE
.PP

.PP
Definition at line \fB39\fP of file \fBwinning\&.c\fP\&.
.PP
References \fBcell_state\fP, \fBcheckIfPlayerWon()\fP, \fBCircle\fP, \fBCross\fP, \fBCellState::last_circle\fP, \fBCellState::last_cross\fP, and \fBNone\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
