TikTakToe: hal_low/timer.c File Reference
timer.c File Reference
#include "hal_low/timer.h"
#include "hal_low/nvic.h"
#include "hal_low/register_access.h"
#include "hal_low/uart.h"
#include <stdint.h>
Functions
void timer_init (Timer const timer)
Default Initialisation of Timer.
void timer_init_detailed (Timer const timer, uint8_t const prescaler, TimerMode const mode, TimerBitMode const bitMode)
Initialises the Timer.
void timer_captureCompareSet (const Timer timer, const TimerCaptureCompare captureCompare, const uint32_t value, const bool shortcutClear)
Set the Capture/ Compare Register of the Timer.
uint32_t timer_captureCompareGet (const Timer timer, const TimerCaptureCompare captureCompare)
Gets the Capture Compare Register of Timer.
void timer_start (const Timer timer)
Starts the given timer.
void timer_stop (const Timer timer)
Stops the given timer.
void timer_count (const Timer timer)
Activate counting on the given timer.
void timer_clear (const Timer timer)
Clear the time of the given timer.
void timer_capture (const Timer timer, const TimerCaptureCompare capture)
Capture the time of the given timer.
void timer_clearCompareEvent (const Timer timer)
Clears the Compare Event for CC[0].
Variables
static const uint32_t TimerBase [3]
static const uint32_t TimerCCOffset [4]
static const uint32_t TimerCaptureTaskOffset [4]
Detailed Description
Author
Date
See also
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file timer.c.
Function Documentation
timer_capture()
void timer_capture (Timer timer, TimerCaptureCompare capture)
Capture the time of the given timer.
Parameters
[in] timer Number of the timer
[in] capture Number of the Capture Compare
Definition at line 128 of file timer.c.
References register_write(), TIMER_TASK_START, TimerBase, and TimerCaptureTaskOffset.
timer_captureCompareGet()
uint32_t timer_captureCompareGet (Timer timer, TimerCaptureCompare captureCompare)
Gets the Capture Compare Register of Timer.
Parameters
timer
captureCompare
Returns
Definition at line 92 of file timer.c.
References register_read(), TimerBase, and TimerCCOffset.
timer_captureCompareSet()
void timer_captureCompareSet (Timer timer, TimerCaptureCompare captureCompare, uint32_t value, bool shortcutClear)
Set the Capture/ Compare Register of the Timer.
It also enables the shortcut between CC[0] and CLEAR, so that the timer is cleared, when the compared value is reached.
Parameters
[in] timer Timer
[in] captureCompare Capture Compare Register
[in] value New Value
[in] shortcutClear
Definition at line 75 of file timer.c.
References register_read(), register_write(), TIMER_SHORTS, TimerBase, and TimerCCOffset.
timer_clear()
void timer_clear (Timer timer)
Clear the time of the given timer.
Parameters
[in] timer Number of the timer
Definition at line 121 of file timer.c.
References register_write(), TIMER_CLEAR, TIMER_TASK_START, and TimerBase.
timer_clearCompareEvent()
void timer_clearCompareEvent (Timer timer)
Clears the Compare Event for CC[0].
This could be useful for stopping the timer from pulling the interrupt-line.
Definition at line 136 of file timer.c.
References register_write(), TIMER_COMPARE_0, TIMER_EVENT_CLEAR, and TimerBase.
timer_count()
void timer_count (Timer timer)
Activate counting on the given timer.
Parameters
[in] timer Number of the timer
Definition at line 114 of file timer.c.
References register_write(), TIMER_COUNT, TIMER_TASK_START, and TimerBase.
timer_init()
void timer_init (Timer timer)
Default Initialisation of Timer.
Initializes the Timer Peripheral to a value ~4sek. This is just for demonstration and could be changed to your needs
Definition at line 44 of file timer.c.
References CC0, TIMER_BIT_MODE_32, timer_captureCompareSet(), timer_init_detailed(), TIMER_MODE_TIMER, and timer_start().
timer_init_detailed()
void timer_init_detailed (Timer timer, uint8_t prescaler, TimerMode mode, TimerBitMode bitMode)
Initialises the Timer.
Compare Value set is for CC[0]
Parameters
[in] prescaler Register value according to Table 147: PRESCALER. value 0..9 is valid ==> 2^0 .. 2^9
[in] bitmode Bit Mode.
Definition at line 52 of file timer.c.
References INT_COMPARE0, Interrupt_ID8, Interrupt_Set_Enable, register_write(), TIMER0_BASE_ADDRESS, TIMER_BITMODE, TIMER_INTENSET, TIMER_PRESCALER, and TimerBase.
timer_start()
void timer_start (Timer timer)
Starts the given timer.
Parameters
[in] timer Number of the timer
Definition at line 100 of file timer.c.
References register_write(), TIMER_START, TIMER_TASK_START, and TimerBase.
timer_stop()
void timer_stop (Timer timer)
Stops the given timer.
Parameters
[in] timer Number of the timer
Definition at line 107 of file timer.c.
References register_write(), TIMER_STOP, TIMER_TASK_START, and TimerBase.
Variable Documentation
TimerBase
const uint32_t TimerBase[3] static
Initial value:
= {
    TIMER0_BASE_ADDRESS,
    TIMER1_BASE_ADDRESS,
    TIMER2_BASE_ADDRESS}
Definition at line 26 of file timer.c.
TimerCaptureTaskOffset
const uint32_t TimerCaptureTaskOffset[4] static
Initial value:
=
    {TIMER_CAPTURE_0, TIMER_CAPTURE_1, TIMER_CAPTURE_2, TIMER_CAPTURE_3}
Definition at line 41 of file timer.c.
TimerCCOffset
const uint32_t TimerCCOffset[4] static
Initial value:
= {
    TIMER_CC_0,
    TIMER_CC_1,
    TIMER_CC_2,
    TIMER_CC_3,
}
Definition at line 31 of file timer.c.