TikTakToe: hal/random.h File Reference
random.h File Reference
Hardware Abstraction Layer
Header file for the RNG HAL.
#include <stdint.h>
Macros
#define RNG_BASE_ADDRESS 0x4000D000
Base address of the RNG peripheral.
#define RNG_START 0x000
Task starting the random number generator.
#define RNG_STOP 0x004
Task stopping the random number generator.
#define RNG_VALRDY 0x100
Event generated when new number is read.
#define RNG_SHORTS 0x200
Shortcut register.
#define RNG_INTEN 0x300
Enable or disable interrupt.
#define RNG_INTENSET 0x304
Enable interrupt.
#define RNG_INTENCLR 0x308
Disable interrupt.
#define RNG_CONFIG 0x504
Configuration register.
#define RNG_VALUE 0x508
Output random number.
#define RNG_TASK_START 1
Value for starting a Task.
#define RNG_EVENT_TRIGGER 1
Value for setting/starting an Event.
#define RNG_EVENT_CLEAR 0
Value for clearing/stopping an Event.
Functions
void rng_init ()
Enables the generation of random numbers.
uint8_t rng_getRandomValue_immediately ()
Get the Random Value from the generator immediately.
uint8_t rng_getRandomValue_waiting ()
Get the Random Value from the generator by polling and waiting.
Detailed Description
Header file for the RNG HAL.
This file contains the declarations and macros for interacting with the RNG peripheral, including initialization and random number retrieval.
See also
random.c
Note
Based on version by Thomas Vogt
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file random.h.
Macro Definition Documentation
RNG_BASE_ADDRESS
#define RNG_BASE_ADDRESS 0x4000D000
Base address of the RNG peripheral.
Definition at line 28 of file random.h.
RNG_CONFIG
#define RNG_CONFIG 0x504
Configuration register.
Definition at line 43 of file random.h.
RNG_EVENT_CLEAR
#define RNG_EVENT_CLEAR 0
Value for clearing/stopping an Event.
Definition at line 49 of file random.h.
RNG_EVENT_TRIGGER
#define RNG_EVENT_TRIGGER 1
Value for setting/starting an Event.
Definition at line 48 of file random.h.
RNG_INTEN
#define RNG_INTEN 0x300
Enable or disable interrupt.
Definition at line 40 of file random.h.
RNG_INTENCLR
#define RNG_INTENCLR 0x308
Disable interrupt.
Definition at line 42 of file random.h.
RNG_INTENSET
#define RNG_INTENSET 0x304
Enable interrupt.
Definition at line 41 of file random.h.
RNG_SHORTS
#define RNG_SHORTS 0x200
Shortcut register.
Definition at line 39 of file random.h.
RNG_START
#define RNG_START 0x000
Task starting the random number generator.
Definition at line 32 of file random.h.
RNG_STOP
#define RNG_STOP 0x004
Task stopping the random number generator.
Definition at line 33 of file random.h.
RNG_TASK_START
#define RNG_TASK_START 1
Value for starting a Task.
Definition at line 47 of file random.h.
RNG_VALRDY
#define RNG_VALRDY 0x100
Event generated when new number is read.
Definition at line 36 of file random.h.
RNG_VALUE
#define RNG_VALUE 0x508
Output random number.
Definition at line 44 of file random.h.
Function Documentation
rng_getRandomValue_immediately()
uint8_t rng_getRandomValue_immediately ()
Get the Random Value from the generator immediately.
The function does not wait for the next value to be generated. It reads the current value from the RNG peripheral.
Returns
uint8_t A random byte.
Definition at line 27 of file random.c.
References register_read(), RNG_BASE_ADDRESS, and RNG_VALUE.
rng_getRandomValue_waiting()
uint8_t rng_getRandomValue_waiting ()
Get the Random Value from the generator by polling and waiting.
This function blocks until the RNG peripheral indicates that a new random value is ready. It then retrieves and returns the random byte.
Returns
uint8_t A random byte.
Definition at line 36 of file random.c.
References register_read(), register_write(), RNG_BASE_ADDRESS, RNG_EVENT_CLEAR, rng_getRandomValue_immediately(), and RNG_VALRDY.
rng_init()
void rng_init ()
Enables the generation of random numbers.
Definition at line 21 of file random.c.
References register_write(), RNG_BASE_ADDRESS, RNG_START, and RNG_TASK_START.