TikTakToe: hal/uart.c File Reference
uart.c File Reference
Implements UART initialization and data transfer functions.
#include "hal/uart.h"
#include "hal/nvic.h"
#include "hal/register_access.h"
#include <stdint.h>
Functions
void uart_init (const bool with_interrupts)
Initializes the UART with the following settings: 115200-8-N-1.
void uart_writeByte (const uint8_t data)
Writes/Sends a byte over the serial port.
uint8_t uart_readByte ()
Reads/Receives a byte from the serial port.
Detailed Description
Implements UART initialization and data transfer functions.
See also
uart.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file uart.c.
Function Documentation
uart_init()
void uart_init (bool with_interrupts)
Initializes the UART with the following settings: 115200-8-N-1.
Parameters
[in] with_interrupts Whether or not interrupts should be triggered.
Definition at line 20 of file uart.c.
References Interrupt_ID2, Interrupt_Set_Enable, register_write(), UART_BASE_ADDRESS, UART_ENABLE, UART_INT_RXDRDY, UART_INTENSET, UART_STARTRX, UART_STARTTX, and UART_TASK_START.
uart_readByte()
uint8_t uart_readByte ()
Reads/Receives a byte from the serial port.
Returns
uint8_t Received byte or 0 (zero) if nothing was received.
Definition at line 62 of file uart.c.
References register_read(), register_write(), UART_BASE_ADDRESS, UART_EVENT_CLEAR, UART_RXD, and UART_RXDRDY.
uart_writeByte()
void uart_writeByte (uint8_t data)
Writes/Sends a byte over the serial port.
Parameters
[in] data Byte to send.
Definition at line 54 of file uart.c.
References register_write(), UART_BASE_ADDRESS, and UART_TXD.