TikTakToe: util/error_handling.c File Reference
error_handling.c File Reference
#include "util/error_handling.h"
#include "presentation/ui.h"
#include "hal/system.h"
#include "hal/uart.h"
#include "presentation/print.h"
#include "presentation/style.h"
Functions
static void handleError (const char *hint)
Handles error messages and resets the system.
void HardFault_Handler ()
Handles hard faults.
void Default_Handler ()
Handles unexpected interrupts.
Function Documentation
Default_Handler()
void Default_Handler ()
Handles unexpected interrupts.
This function is triggered when an unexpected interrupt occurs. It provides a mechanism to handle the interrupt and display an appropriate message.
Definition at line 31 of file error_handling.c.
References handleError().
handleError()
static void handleError (const char * hint) static
Handles error messages and resets the system.
This function clears the console, displays an error message, and waits for user input before attempting a soft reset of the system.
Parameters
[in] hint A message providing details about the error.
Note
Depending on the error, the system may not be able to recover or even execute this function properly.
Definition at line 37 of file error_handling.c.
References BOLD, DIM, FG_RED, print(), print_clearConsole(), println(), RESET, system_softReset(), uart_readByte(), and ui_printHeading().
HardFault_Handler()
void HardFault_Handler ()
Handles hard faults.
This function is triggered when a hard fault occurs. It provides a mechanism to handle the fault and display an appropriate message.
Definition at line 25 of file error_handling.c.
References handleError().