.TH "util Directory Reference" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconversion\&.h\fP"
.br
.ti -1c
.RI "file \fBerror_handling\&.h\fP"
.br
.ti -1c
.RI "file \fBmath\&.h\fP"
.br
.in -1c
