.TH "CellSize" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CellSize \- Struct representing the dimensions of a cell\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cell\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSize\fP \fBsize\fP"
.br
.RI "Current size of the cell\&. "
.ti -1c
.RI "uint8_t \fBwidth\fP"
.br
.RI "Width of the cell\&. "
.ti -1c
.RI "uint8_t \fBheight\fP"
.br
.RI "Height of the cell\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct representing the dimensions of a cell\&. 
.PP
Definition at line \fB49\fP of file \fBcell\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t CellSize::height"

.PP
Height of the cell\&. 
.PP
Definition at line \fB53\fP of file \fBcell\&.h\fP\&.
.SS "\fBSize\fP CellSize::size"

.PP
Current size of the cell\&. 
.PP
Definition at line \fB51\fP of file \fBcell\&.h\fP\&.
.SS "uint8_t CellSize::width"

.PP
Width of the cell\&. 
.PP
Definition at line \fB52\fP of file \fBcell\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
