.TH "config.h" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCELLS_PER_ROW\fP   @CELLS_PER_ROW @"
.br
.RI "Number of cells per row in the game grid\&. "
.ti -1c
.RI "#define \fBCELLS_PER_COL\fP   @CELLS_PER_COL @"
.br
.RI "Number of cells per column in the game grid\&. "
.ti -1c
.RI "#define \fBTICKS_PER_TURN\fP   @TICKS_PER_TURN @"
.br
.RI "Number of ticks allowed per turn\&. "
.ti -1c
.RI "#define \fBTICK_SPEED\fP   @TICK_SPEED @"
.br
.RI "Speed of each tick in milliseconds\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CELLS_PER_COL   @CELLS_PER_COL @"

.PP
Number of cells per column in the game grid\&. This macro defines the vertical size of the game grid\&. 
.PP
Definition at line \fB60\fP of file \fBconfig\&.h\fP\&.
.SS "#define CELLS_PER_ROW   @CELLS_PER_ROW @"

.PP
Number of cells per row in the game grid\&. This macro defines the horizontal size of the game grid\&. 
.PP
Definition at line \fB51\fP of file \fBconfig\&.h\fP\&.
.SS "#define TICK_SPEED   @TICK_SPEED @"

.PP
Speed of each tick in milliseconds\&. This macro defines the duration of each tick in the game loop\&. 
.PP
Definition at line \fB78\fP of file \fBconfig\&.h\fP\&.
.SS "#define TICKS_PER_TURN   @TICKS_PER_TURN @"

.PP
Number of ticks allowed per turn\&. This macro defines the maximum number of ticks a player has to make a move\&. 
.PP
Definition at line \fB69\fP of file \fBconfig\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
