.TH "presentation/cursor.c" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/cursor.c \- Implements cursor movement functionality for the presentation layer\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'presentation/cursor\&.h'\fP
.br
\fR#include 'presentation/print\&.h'\fP
.br
\fR#include 'util/conversion\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBwriteNumToBuf\fP (uint8_t num, const char *num_buf, char *buf, uint8_t *buf_pos)"
.br
.RI "Write a numeric value to a buffer\&. "
.ti -1c
.RI "void \fBcursor_moveTo\fP (const uint8_t x, const uint8_t y)"
.br
.RI "Move the cursor to the given coordinates\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements cursor movement functionality for the presentation layer\&. 


.PP
\fBSee also\fP
.RS 4
\fBcursor\&.h\fP
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBcursor\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void cursor_moveTo (uint8_t x, uint8_t y)"

.PP
Move the cursor to the given coordinates\&. This function generates an escape sequence to move the cursor to the specified (x, y) position on the terminal\&.
.PP
\fBParameters\fP
.RS 4
\fIx\fP X-coordinate of the cursor position\&. 
.br
\fIy\fP Y-coordinate of the cursor position\&.
.RE
.PP
\fBNote\fP
.RS 4
This function can be improved by using new functions found in the conversion module and directly writing the string representation of the number to the target buffer\&. 
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBcursor\&.c\fP\&.
.PP
References \fBint_to_str()\fP, \fBprint()\fP, and \fBwriteNumToBuf()\fP\&.
.SS "static void writeNumToBuf (uint8_t num, const char * num_buf, char * buf, uint8_t * buf_pos)\fR [static]\fP"

.PP
Write a numeric value to a buffer\&. This function writes the string representation of a numeric value to a buffer while maintaining the current position in the buffer\&.
.PP
\fBParameters\fP
.RS 4
\fInum\fP The numeric value to write\&. 
.br
\fInum_buf\fP A buffer containing the string representation of the number\&. 
.br
\fIbuf\fP The target buffer to write to\&. 
.br
\fIbuf_pos\fP Pointer to the current position in the target buffer\&. 
.RE
.PP

.PP
Definition at line \fB60\fP of file \fBcursor\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
