.TH "presentation/cursor.h" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
presentation/cursor.h \- Contains functions for moving the presentation of the cursor\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcursor_moveTo\fP (uint8_t x, uint8_t y)"
.br
.RI "Move the cursor to the given coordinates\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains functions for moving the presentation of the cursor\&. 

This file provides the interface for cursor movement in the presentation layer\&.
.PP
\fBSee also\fP
.RS 4
\fBcursor\&.c\fP
.RE
.PP
\fBCopyright\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.RE
.PP

.PP
Definition in file \fBcursor\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void cursor_moveTo (uint8_t x, uint8_t y)"

.PP
Move the cursor to the given coordinates\&. This function generates an escape sequence to move the cursor to the specified (x, y) position on the terminal\&.
.PP
\fBParameters\fP
.RS 4
\fIx\fP X-coordinate of the cursor position\&. 
.br
\fIy\fP Y-coordinate of the cursor position\&.
.RE
.PP
\fBNote\fP
.RS 4
This function can be improved by using new functions found in the conversion module and directly writing the string representation of the number to the target buffer\&. 
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBcursor\&.c\fP\&.
.PP
References \fBint_to_str()\fP, \fBprint()\fP, and \fBwriteNumToBuf()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
