.TH "util/error_handling.c" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/error_handling.c
.SH SYNOPSIS
.br
.PP
\fR#include 'util/error_handling\&.h'\fP
.br
\fR#include 'presentation/ui\&.h'\fP
.br
\fR#include 'hal/system\&.h'\fP
.br
\fR#include 'hal/uart\&.h'\fP
.br
\fR#include 'presentation/print\&.h'\fP
.br
\fR#include 'presentation/style\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBhandleError\fP (const char *hint)"
.br
.RI "Handles error messages and resets the system\&. "
.ti -1c
.RI "void \fBHardFault_Handler\fP ()"
.br
.RI "Handles hard faults\&. "
.ti -1c
.RI "void \fBDefault_Handler\fP ()"
.br
.RI "Handles unexpected interrupts\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Default_Handler ()"

.PP
Handles unexpected interrupts\&. This function is triggered when an unexpected interrupt occurs\&. It provides a mechanism to handle the interrupt and display an appropriate message\&. 
.PP
Definition at line \fB31\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SS "static void handleError (const char * hint)\fR [static]\fP"

.PP
Handles error messages and resets the system\&. This function clears the console, displays an error message, and waits for user input before attempting a soft reset of the system\&.
.PP
\fBParameters\fP
.RS 4
\fIhint\fP A message providing details about the error\&.
.RE
.PP
\fBNote\fP
.RS 4
Depending on the error, the system may not be able to recover or even execute this function properly\&. 
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBBOLD\fP, \fBDIM\fP, \fBFG_RED\fP, \fBprint()\fP, \fBprint_clearConsole()\fP, \fBprintln()\fP, \fBRESET\fP, \fBsystem_softReset()\fP, \fBuart_readByte()\fP, and \fBui_printHeading()\fP\&.
.SS "void HardFault_Handler ()"

.PP
Handles hard faults\&. This function is triggered when a hard fault occurs\&. It provides a mechanism to handle the fault and display an appropriate message\&. 
.PP
Definition at line \fB25\fP of file \fBerror_handling\&.c\fP\&.
.PP
References \fBhandleError()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
