.TH "Style" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Style \- Represents a style with foreground color, background color, and font style\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <style\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfg_color\fP"
.br
.RI "Foreground color escape sequence\&. "
.ti -1c
.RI "char * \fBbg_color\fP"
.br
.RI "Background color escape sequence\&. "
.ti -1c
.RI "char * \fBfont_style\fP"
.br
.RI "Font style escape sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a style with foreground color, background color, and font style\&. 

This struct is used to define a combination of terminal styling attributes\&. 
.PP
Definition at line \fB29\fP of file \fBstyle\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* Style::bg_color"

.PP
Background color escape sequence\&. 
.PP
Definition at line \fB32\fP of file \fBstyle\&.h\fP\&.
.SS "char* Style::fg_color"

.PP
Foreground color escape sequence\&. 
.PP
Definition at line \fB31\fP of file \fBstyle\&.h\fP\&.
.SS "char* Style::font_style"

.PP
Font style escape sequence\&. 
.PP
Definition at line \fB33\fP of file \fBstyle\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
