.TH "Utility" 3 "Tue Jan 1 1980 00:00:00" "Version 1.0.0" "TikTakToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utility \- Utility
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdef\&.h\fP"
.br
.RI "Contains very basic and general definitions\&. "
.ti -1c
.RI "file \fBconversion\&.h\fP"
.br
.RI "Contains several different simple and independent conversion functions\&. "
.ti -1c
.RI "file \fBerror_handling\&.h\fP"
.br
.RI "Contains functions to react on errors\&. "
.ti -1c
.RI "file \fBinput_buf\&.h\fP"
.br
.RI "Contains everything for the input buffer\&. "
.ti -1c
.RI "file \fBmath\&.h\fP"
.br
.RI "Contains several different simple and independent math functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
This group contains all utility modules\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for TikTakToe from the source code\&.
