TikTakToe: hal/interrupts.h File Reference
interrupts.h File Reference
Hardware Abstraction Layer
Contains the relevant interrupt handlers.
Functions
void Interrupt2_Handler ()
UART interrupt handler.
void Interrupt8_Handler ()
Timer interrupt handler.
Detailed Description
Contains the relevant interrupt handlers.
This file declares the interrupt handler functions for UART and Timer interrupts. These handlers are triggered by specific hardware events and perform the necessary actions to handle the interrupts.
See also
interrupts.c
Note
Ensure the corresponding peripherals are properly configured before enabling these interrupts.
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file interrupts.h.
Function Documentation
Interrupt2_Handler()
void Interrupt2_Handler ()
UART interrupt handler.
This function is triggered when a UART interrupt occurs. It reads a byte from the UART peripheral and processes it using the input buffer. The interrupt pending bit is cleared after handling the interrupt.
See also
uart_readByte
Definition at line 23 of file interrupts.c.
References input_onInterrupt(), Interrupt_ICPR, Interrupt_ID2, register_write(), and uart_readByte().
Interrupt8_Handler()
void Interrupt8_Handler ()
Timer interrupt handler.
This function is triggered when a timer interrupt occurs. It resets the timer compare register and clears the interrupt pending bit. Additionally, it notifies the time module about the interrupt event.
See also
time_onInterrupt
Definition at line 29 of file interrupts.c.
References Interrupt_ICPR, Interrupt_ID8, register_write(), time_onInterrupt(), TIMER0_BASE_ADDRESS, and TIMER_COMPARE_0.