TikTakToe: logic/game.c File Reference
game.c File Reference
Implements the core game logic for Tic-Tac-Toe.
#include "logic/game.h"
#include "config.h"
#include "hal/nvic.h"
#include "hal/random.h"
#include "hal/timer.h"
#include "logic/bot.h"
#include "logic/input.h"
#include "logic/time.h"
#include "logic/winning.h"
#include "presentation/cell.h"
#include "presentation/field.h"
#include "presentation/menu.h"
#include "presentation/print.h"
#include "presentation/style.h"
#include "presentation/ui.h"
#include "util/input_buf.h"
#include "util/math.h"
#include <stdint.h>
Functions
static void init (Mode mode)
Initializes relevant things at the game start.
static void handleForcedMoveUpdate ()
Handles the presentation update, when a move is forced due to timeout.
static void redrawField ()
Refreshes the whole UI.
static void calculateSummary ()
Calculates game summary statistics.
static Player startingPlayer ()
Randomly determines the starting player.
void game_run (const Mode mode)
Start the main game.
void game_onTimeOut ()
Automatically end a turn in case the turn time is over.
void game_endTurn ()
Finish the current turn.
Variables
volatile bool force_ui_update = false
Force an update of the UI.
static GameState game_state
GameState of the current game.
static CellState cell_state
CellState of the current game.
Detailed Description
Implements the core game logic for Tic-Tac-Toe.
See also
game.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file game.c.
Function Documentation
calculateSummary()
static void calculateSummary () static
Calculates game summary statistics.
Computes total and average ticks for each player and the game overall.
Note
Statistics are written to the game_state struct.
See also
game_state
Definition at line 246 of file game.c.
References GameState::average_ticks, Circle, GameState::circle_average_ticks, GameState::circle_total_ticks, Cross, GameState::cross_average_ticks, GameState::cross_total_ticks, g_timer, game_state, GameState::mode, PVE, GameState::round, GameTimer::ticks_total, GameState::total_ticks, and GameState::winner.
game_endTurn()
void game_endTurn ()
Finish the current turn.
Updates the game state and switches to the next player or round.
Definition at line 169 of file game.c.
References cell_state, Circle, Cross, GameState::current_player, GameState::fields_marked, game_state, CellState::last_circle, CellState::last_cross, GameState::mode, PVE, GameState::round, CellState::selected, and time_finishTurn().
game_onTimeOut()
void game_onTimeOut ()
Automatically end a turn in case the turn time is over.
See also
time_onInterrupt
Definition at line 149 of file game.c.
References CellState::all, bot_markRandomCell(), cell_state, Circle, Cross, GameState::current_player, force_ui_update, game_endTurn(), game_state, CellState::last_circle, CellState::last_cross, GameState::mode, and PVE.
game_run()
void game_run (const Mode mode)
Start the main game.
Initializes the game and enters the main game loop.
Parameters
[in] mode Which mode the game should be played in.
Definition at line 82 of file game.c.
References __WFI, CellState::all, BOLD, bot_markRandomCell(), calculateSummary(), cell_redraw_withModifier(), cell_redrawAll(), cell_select(), cell_state, CELLS_PER_COL, CELLS_PER_ROW, Circle, Cross, GameState::current_player, GameState::fields_marked, force_ui_update, g_input_buf, g_timer, game_state, handleForcedMoveUpdate(), init(), input_getNext(), input_handleByte(), GameTimer::is_running, CellState::last_circle, max, menu_showGameOver(), GameState::mode, None, PVE, redrawField(), REMAINING_TIME, GameState::round, CellState::selected, TICKS_PER_TURN, TIMER0, timer_stop(), ui_updateTimer(), ui_updateTurn(), GameState::winner, and winning_checkForWinner().
handleForcedMoveUpdate()
static void handleForcedMoveUpdate () static
Handles the presentation update, when a move is forced due to timeout.
Definition at line 286 of file game.c.
References CellState::all, cell_select(), cell_state, Circle, GameState::current_player, game_state, CellState::last_circle, CellState::last_cross, GameState::mode, PVE, GameState::round, CellState::selected, and ui_updateTurn().
init()
static void init (Mode mode) static
Initializes relevant things at the game start.
Sets up the game/cell state, initializes the input buffer, and prepares the UI.
Parameters
[in] mode The game mode (PVE or PVP).
Definition at line 198 of file game.c.
References CellState::all, cell_select(), cell_state, CELLS_PER_COL, CELLS_PER_ROW, GameState::current_player, FIRST_ROUND, g_input_buf, game_state, HIDE_CURSOR, input_init(), Cell::marked_by, None, print(), print_clearConsole(), redrawField(), rng_init(), CellState::selected, startingPlayer(), time_init(), and ui_printStartingPlayer().
redrawField()
static void redrawField () static
Refreshes the whole UI.
Clears the console and redraws the game field and UI elements.
Definition at line 275 of file game.c.
References CellState::all, cell_redrawAll(), cell_select(), cell_state, GameState::current_player, field_redraw(), game_state, print_clearConsole(), REMAINING_TIME, GameState::round, CellState::selected, TICKS_PER_TURN, ui_displayTimer(), ui_displayTurn(), and ui_printHeading().
startingPlayer()
static Player startingPlayer () static
Randomly determines the starting player.
Definition at line 308 of file game.c.
References rng_getRandomValue_waiting().
Variable Documentation
cell_state
CellState cell_state static
CellState of the current game.
Definition at line 40 of file game.c.
force_ui_update
volatile bool force_ui_update = false
Force an update of the UI.
Definition at line 36 of file game.c.
game_state
GameState game_state static
GameState of the current game.
Definition at line 38 of file game.c.