TikTakToe: logic/time.c File Reference
time.c File Reference
Implements time-related functionality for the game.
#include "logic/time.h"
#include "hal/timer.h"
#include "logic/game.h"
#include <stdint.h>
Functions
void time_init ()
Initializes the timer.
void time_onInterrupt ()
Increments the ticks and can finish the round.
void time_finishTurn (GameState *game_state)
Resets the ticks.
void time_pause ()
Pause the timer.
void time_resume ()
Resume the timer when paused.
Variables
GameTimer g_timer
Global game timer instance.
Detailed Description
Implements time-related functionality for the game.
See also
time.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file time.c.
Function Documentation
time_finishTurn()
void time_finishTurn (GameState * game_state)
Resets the ticks.
Resets the turn-specific tick counter and updates the game state with the elapsed time for the current player.
Parameters
[in,out] game_state Current state of the game
Definition at line 42 of file time.c.
References GameState::circle_total_ticks, Cross, GameState::cross_total_ticks, GameState::current_player, g_timer, game_state, and GameTimer::ticks_turn.
time_init()
void time_init ()
Initializes the timer.
Sets up the hardware timer with the appropriate configuration for the game.
Definition at line 25 of file time.c.
References CC0, TICK_SPEED, TIMER0, TIMER_BIT_MODE_32, timer_captureCompareSet(), timer_init_detailed(), and timer_start().
time_onInterrupt()
void time_onInterrupt ()
Increments the ticks and can finish the round.
This function is called on a timer interrupt. It increments the total and turn-specific tick counters and triggers a timeout if the turn duration is exceeded.
Definition at line 32 of file time.c.
References g_timer, game_onTimeOut(), TICKS_PER_TURN, GameTimer::ticks_total, and GameTimer::ticks_turn.
time_pause()
void time_pause ()
Pause the timer.
Stops the hardware timer and marks the timer as not running.
Definition at line 58 of file time.c.
References g_timer, GameTimer::is_running, TIMER0, and timer_stop().
time_resume()
void time_resume ()
Resume the timer when paused.
Restarts the hardware timer and marks the timer as running.
Definition at line 64 of file time.c.
References g_timer, GameTimer::is_running, TIMER0, and timer_start().
Variable Documentation
g_timer
GameTimer g_timer
Initial value:
= (GameTimer){
    .ticks_total = 0,
    .ticks_turn = 0,
    .is_running = true,
}
Global game timer instance.
This global variable tracks the timer state and tick counts for the game.
Definition at line 19 of file time.c.