TikTakToe: logic/input.h File Reference
input.h File Reference
Logic Layer
Contains the input handling of the game.
#include "def.h"
#include "logic/game.h"
Functions
bool input_handleByte (const uint8_t *byte, GameState *game_state, CellState *cell_state)
Handles an input byte and updates game and cell states.
Detailed Description
Contains the input handling of the game.
This file provides the interface for handling user input during the game, including processing key presses and updating game and cell states.
See also
input.c
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file input.h.
Function Documentation
input_handleByte()
bool input_handleByte (const uint8_t * byte, GameState * game_state, CellState * cell_state)
Handles an input byte and updates game and cell states.
Processes the input byte to determine the appropriate action, such as marking a cell, navigating the board, or pausing the game. Updates the game state and cell state accordingly.
Parameters
[in] byte The input byte to process.
[in,out] game_state Pointer to the current game state.
[in,out] cell_state Pointer to the current cell state.
Returns
True if a field redraw is needed, false otherwise.
Definition at line 79 of file input.c.
References cell_decreaseSize(), cell_increaseSize(), cell_state, g_timer, game_state, handleEscapeSequence(), handlePauseResume(), handleSetMark(), GameTimer::is_running, and openControls().