TikTakToe: presentation/cell.c File Reference
cell.c File Reference
Implements functions for managing the presentation of cells.
#include "presentation/cell.h"
#include "logic/game.h"
#include "presentation/cursor.h"
#include "presentation/field.h"
#include "presentation/print.h"
#include "presentation/style.h"
Functions
static void redrawCell (uint8_t row, uint8_t col, const char *modifier, Player marked_by)
Redraws a single cell at the specified position.
void cell_redraw (const Cell *cell)
Redraws the given cell.
void cell_redraw_withModifier (const Cell *cell, const char *modifier)
Redraws the given cell with a modifier.
void cell_select (const Cell *cell)
Selects the given cell.
void cell_redrawAll (Cell all_cells[][CELLS_PER_ROW], const char *modifier)
Redraws the entire field of cells.
void cell_increaseSize ()
Increases the size of the cells.
void cell_decreaseSize ()
Decreases the size of the cells.
Variables
CellSize g_cell_size
Global variable representing the current cell size.
static char * SMALL_X [1][3] = {{" ", "X", " "}}
Representation of a small 'X'.
static char * SMALL_O [1][3] = {{" ", "O", " "}}
Representation of a small 'O'.
static char * MEDIUM_X [3][7]
static char * MEDIUM_O [3][7]
static char * LARGE_X [5][9]
static char * LARGE_O [5][9]
static CellSize VALID_SIZES []
Array of valid cell sizes.
Detailed Description
Implements functions for managing the presentation of cells.
See also
cell.h
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file cell.c.
Function Documentation
cell_decreaseSize()
void cell_decreaseSize ()
Decreases the size of the cells.
Definition at line 160 of file cell.c.
References g_cell_size, CellSize::height, CellSize::size, Small, VALID_SIZES, and CellSize::width.
cell_increaseSize()
void cell_increaseSize ()
Increases the size of the cells.
Definition at line 149 of file cell.c.
References g_cell_size, CellSize::height, Large, CellSize::size, VALID_SIZES, and CellSize::width.
cell_redraw()
void cell_redraw (const Cell * cell)
Redraws the given cell.
Parameters
[in] cell Cell to redraw.
Definition at line 101 of file cell.c.
References Cell::col, Cell::marked_by, redrawCell(), and Cell::row.
cell_redraw_withModifier()
void cell_redraw_withModifier (const Cell * cell, const char * modifier)
Redraws the given cell with a modifier.
Parameters
[in] cell Cell to redraw.
[in] modifier Modifier to apply during redraw.
Definition at line 106 of file cell.c.
References Cell::col, Cell::marked_by, redrawCell(), and Cell::row.
cell_redrawAll()
void cell_redrawAll (Cell all_cells[][CELLS_PER_ROW], const char * modifier)
Redraws the entire field of cells.
Parameters
[in] all_cells 2D array of cells representing the field.
[in] modifier Modifier to apply during redraw.
Definition at line 136 of file cell.c.
References CELLS_PER_COL, CELLS_PER_ROW, Cell::col, Cell::marked_by, redrawCell(), and Cell::row.
cell_select()
void cell_select (const Cell * cell)
Selects the given cell.
Parameters
[in] cell Cell to select.
Definition at line 111 of file cell.c.
References Cell::col, INVERSE, Cell::marked_by, redrawCell(), and Cell::row.
redrawCell()
static void redrawCell (uint8_t row, uint8_t col, const char * modifier, Player marked_by) static
Redraws a single cell at the specified position.
Parameters
[in] row Y-position of the cell.
[in] col X-position of the cell.
[in] modifier Modifier to apply during redraw.
[in] marked_by Player marking the cell.
Definition at line 172 of file cell.c.
References Circle, Cross, cursor_moveTo(), DEFAULT_CIRCLE, DEFAULT_CROSS, FIELD_X_OFFSET, FIELD_Y_OFFSET, g_cell_size, CellSize::height, Large, LARGE_O, LARGE_X, Medium, MEDIUM_O, MEDIUM_X, None, print(), print_style(), RESET, CellSize::size, Small, SMALL_O, SMALL_X, and CellSize::width.
Variable Documentation
g_cell_size
CellSize g_cell_size
Initial value:
= (CellSize){
    .size = INITIAL_SIZE,
    .height = INITIAL_HEIGHT,
    .width = INITIAL_WIDTH,
}
Global variable representing the current cell size.
Initialized with default values for size, height, and width.
See also
VALID_SIZES
INITIAL_SIZE
INITIAL_HEIGHT
INITIAL_WIDTH
Definition at line 22 of file cell.c.
LARGE_O
char* LARGE_O[5][9] static
Initial value:
= {
    {" ",
     CORNER_TOP_LEFT,
     TOP_BOTTOM,
     TOP_BOTTOM,
     TOP_BOTTOM,
     TOP_BOTTOM,
     TOP_BOTTOM,
     CORNER_TOP_RIGHT,
     " "},
    {" ", SIDE, " ", " ", " ", " ", " ", SIDE, " "},
    {" ", SIDE, " ", " ", " ", " ", " ", SIDE, " "},
    {" ", SIDE, " ", " ", " ", " ", " ", SIDE, " "},
    {" ",
     CORNER_BOT_LEFT,
     TOP_BOTTOM,
     TOP_BOTTOM,
     TOP_BOTTOM,
     TOP_BOTTOM,
     TOP_BOTTOM,
     CORNER_BOT_RIGHT,
     " "},
}
Definition at line 63 of file cell.c.
LARGE_X
char* LARGE_X[5][9] static
Initial value:
= {
    {" ", " ", DIAGONAL_BW, " ", " ", " ", DIAGONAL_FW, " ", " "},
    {" ", " ", " ", DIAGONAL_BW, " ", DIAGONAL_FW, " ", " ", " "},
    {" ", " ", " ", " ", DIAGONAL_MID, " ", " ", " ", " "},
    {" ", " ", " ", DIAGONAL_FW, " ", DIAGONAL_BW, " ", " ", " "},
    {" ", " ", DIAGONAL_FW, " ", " ", " ", DIAGONAL_BW, " ", " "},
}
Definition at line 55 of file cell.c.
MEDIUM_O
char* MEDIUM_O[3][7] static
Initial value:
= {
    {" ", CORNER_TOP_LEFT, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, CORNER_TOP_RIGHT, " "},
    {" ", SIDE, " ", " ", " ", SIDE, " "},
    {" ", CORNER_BOT_LEFT, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, CORNER_BOT_RIGHT, " "},
}
Definition at line 49 of file cell.c.
MEDIUM_X
char* MEDIUM_X[3][7] static
Initial value:
= {
    {" ", " ", DIAGONAL_BW, " ", DIAGONAL_FW, " ", " "},
    {" ", " ", " ", DIAGONAL_MID, " ", " ", " "},
    {" ", " ", DIAGONAL_FW, " ", DIAGONAL_BW, " ", " "},
}
Definition at line 43 of file cell.c.
SMALL_O
char* SMALL_O[1][3] = {{" ", "O", " "}} static
Representation of a small 'O'.
Definition at line 41 of file cell.c.
SMALL_X
char* SMALL_X[1][3] = {{" ", "X", " "}} static
Representation of a small 'X'.
Definition at line 40 of file cell.c.
VALID_SIZES
CellSize VALID_SIZES[] static
Initial value:
= {
    {.width = 4, .height = 3},
    {.width = 8, .height = 5},
    {.width = 10, .height = 7},
}
Array of valid cell sizes.
Each entry contains the width and height for a specific size.
Definition at line 95 of file cell.c.