name: Build and Push Dockerimage

on:
  push:
    branches: ['main']
    paths:
      - '**.c'
      - '**.h'
      - Dockerfile
    tag:
  workflow_dispatch:

env:
    GHCR: ghcr.io
    DR: index.docker.io
    DR_IMAGE_NAME: tiktaktoe
    GHCR_IMAGE_NAME: ${{ github.repository }}

jobs:
    dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ secrets.DOCKERHUB_USERNAME}}/${{ env.DR_IMAGE_NAME }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                annotations: ${{ steps.meta.outputs.annotations }}
                provenance: true
                sbom: true

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v2
              with:
                subject-name: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DR_IMAGE_NAME }}
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true

    ghcr:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4


            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.GHCR }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.GHCR }}/${{ env.GHCR_IMAGE_NAME }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                provenance: true
                sbom: true

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v2
              with:
                subject-name: ${{ env.GHCR }}/${{ env.GHCR_IMAGE_NAME }}
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true

